{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "BeamPolyCut",
  "ElementResolver": {
    "ResolutionMap": {
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Vector": {
        "Key": "Autodesk.DesignScript.Geometry.Vector",
        "Value": "ProtoGeometry.dll"
      },
      "CoordinateSystem": {
        "Key": "Autodesk.DesignScript.Geometry.CoordinateSystem",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "Point.ByCoordinates(0,0,0);\nPoint.ByCoordinates(2002,1200,0);\nPoint.ByCoordinates(3000,2000,0);\nVector.ZAxis();",
      "Id": "dfd42be4c2504811ad500ca9cd116013",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "e681ea471bb04ebeb415434b2a3f1dd4",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6b4ec83623de423abbf413fffab2657e",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8a81ab202c4348fb9116faea8e605dde",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "944273d75a3a49be8351524bd5ecf48e",
          "Name": "",
          "Description": "Value of expression at line 4",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Arc.ByThreePoints@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "5419ea8bf2b84c9e8eecde66f2c7c9ce",
      "Inputs": [
        {
          "Id": "10090418f58a4649a8ccc00b4137335e",
          "Name": "firstPoint",
          "Description": "First point along the curve\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8825e515164d4bdfbf043ebb20a326c0",
          "Name": "secondPoint",
          "Description": "Second point along the curve\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "dca09aaa41834564b2f259aee3c037a0",
          "Name": "thirdPoint",
          "Description": "Third point along the curve\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9c9be684b0ba4c38856eb8baaefbb4b3",
          "Name": "Arc",
          "Description": "An Arc",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an arc by providing three sequential points along its circumference.\n\nArc.ByThreePoints (firstPoint: Point, secondPoint: Point, thirdPoint: Point): Arc"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "Point.ByCoordinates(0,0,0);\nPoint.ByCoordinates(0,1200,0);\nVector.ZAxis();",
      "Id": "e4dd7650158d4d959d7a03f935d3d716",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "08fdd18d998a44d0b613a0c8c3853afb",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "48562331105249058fc9af59a46d179a",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9388406200eb4610b170de31c33a4836",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Beams.BentBeam.ByArc@Autodesk.DesignScript.Geometry.Arc,Autodesk.DesignScript.Geometry.Vector,int,bool,AdvanceSteel.Nodes.Property[]",
      "Id": "8478e324a10247059314a826842e6254",
      "Inputs": [
        {
          "Id": "5dca5c696f264a1295510a7d3b145072",
          "Name": "arc",
          "Description": "Input Dynamo Node\n\nArc",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "26f8db7b2cc44401b2be9b1f3c9d9320",
          "Name": "orientation",
          "Description": "Section orientation\n\nVector\nDefault value : Autodesk.DesignScript.Geometry.Vector.ZAxis()",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "92fcf3b5d5334159809efdac5d195dce",
          "Name": "refAxis",
          "Description": "Input Beam reference axis UpperLeft = 0, UpperSys = 1, UpperRight = 2, MidLeft = 3, SysSys = 4, MidRight = 5, LowerLeft = 6, LowerSys = 7, LowerRight = 8, ContourCenter = 9\n\nint\nDefault value : 5",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "265a8d5e45ea439c9a89c41b5211e3c9",
          "Name": "crossSectionMirror",
          "Description": "Input Beam Mirror Option\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "029046d97d914a7fa706bbfc155c303a",
          "Name": "additionalBeamParameters",
          "Description": "Optional Input Beam Build Properties\n\nProperty[]\nDefault value : null",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "05fd9c6ff4124503867582e87bf0e578",
          "Name": "BentBeam",
          "Description": "BentBeam",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel bent beam on a Dynamo Arc- inc ModelRole and Section Size\n\nBentBeam.ByArc (arc: Arc, orientation: Vector = Autodesk.DesignScript.Geometry.Vector.ZAxis(), refAxis: int = 5, crossSectionMirror: bool = false, additionalBeamParameters: Property[] = null): BentBeam"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Beams.StraightBeam.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,int,bool,AdvanceSteel.Nodes.Property[]",
      "Id": "9d84acd3b9a44e5ba50417c5d72ce251",
      "Inputs": [
        {
          "Id": "38de213b017b4312b5a96b8fbced50b1",
          "Name": "start",
          "Description": "Input Start point of Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "198478efc5914f87aac804cf112d854e",
          "Name": "end",
          "Description": "Input End point of Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b425d2fe92b24cc2ab6d6ba2327ea075",
          "Name": "orientation",
          "Description": "Section orientation\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7ac0fba34f124500b1b1f57d60f6cf93",
          "Name": "refAxis",
          "Description": "int\nDefault value : 5",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "003b88a77a304db582ff6a6737c0e9b1",
          "Name": "crossSectionMirror",
          "Description": "bool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "23bb293d2032425692169c4cdb9c274c",
          "Name": "additionalBeamParameters",
          "Description": "Optional Input Beam Build Properties\n\nProperty[]\nDefault value : null",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7ec4244781a94481a88374cbb51075b9",
          "Name": "StraightBeam",
          "Description": "StraightBeam",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel straight beam between two points\n\nStraightBeam.ByStartPointEndPoint (start: Point, end: Point, orientation: Vector, refAxis: int = 5, crossSectionMirror: bool = false, additionalBeamParameters: Property[] = null): StraightBeam"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "4;",
      "Id": "632811afea3a41e98058e8d607a1ba7f",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a5b5c312c2b94893a288db354fe1657c",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "CoordinateSystem.ByOriginVectors(Point.ByCoordinates(0,1000,0),Vector.XAxis(),Vector.Reverse(Vector.ZAxis()),Vector.YAxis());",
      "Id": "88680ee8886d4b249cf25885c2e16ac5",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "e120405fc56c436ba5979a72f7644cc2",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "CoordinateSystem.ByOriginVectors(Point.ByCoordinates(2573,1639,0),Vector.XAxis(),Vector.Reverse(Vector.ZAxis()),Vector.YAxis());",
      "Id": "84e3f6fb5b6b4fed997a561a2493e7b0",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "fe544ccc577945c3bf5ed7997f486e70",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "100;",
      "Id": "5551985c74ea49c09d12a073601c5a3e",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "1fdf33061c1f4fb8b1955ce4af970299",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "1000;",
      "Id": "69fb51abd8cc4fbaa2f2a0f067a3d1ab",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "284e9c1814244ef583ca71a8d8218311",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "Point.ByCoordinates(5001,0,0);\nPoint.ByCoordinates(5000,1200,0);\nVector.ZAxis();\nPoint.ByCoordinates(5000,600,0);",
      "Id": "437411a14fc9472e8dce741b0a37a2ef",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "52769b394b474d3b9fb2afc26a286a4e",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "166c69eabe59414d8962bde09576e2d7",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f99f8617fe744eddbd43f5c9b1cd6325",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0a1ae22b8f4949a2a1e9fbd3ecd183e2",
          "Name": "",
          "Description": "Value of expression at line 4",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "1;",
      "Id": "f9e29ee32fce416cb2fde464e48c5441",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "cc5e23a18638401e9051534f9d3b75b0",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Beams.StraightBeam.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,int,bool,AdvanceSteel.Nodes.Property[]",
      "Id": "72e5789e1e0c4778bc8686044559bede",
      "Inputs": [
        {
          "Id": "08966f7025534e578f7e71c738432405",
          "Name": "start",
          "Description": "Input Start point of Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d61473af30bd460bb098462808e33701",
          "Name": "end",
          "Description": "Input End point of Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e9c694c0631941beba9ce2c94d65fe69",
          "Name": "orientation",
          "Description": "Section orientation\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "236f9a8e630a480e82ffcb53016f5c41",
          "Name": "refAxis",
          "Description": "int\nDefault value : 5",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "60c81d2b455040f0b0a9f742485dcfa4",
          "Name": "crossSectionMirror",
          "Description": "bool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a7101749276e4095b1a5a0e00c58facd",
          "Name": "additionalBeamParameters",
          "Description": "Optional Input Beam Build Properties\n\nProperty[]\nDefault value : null",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e1d6461ab96a4c36ab0b8f164144a2ef",
          "Name": "StraightBeam",
          "Description": "StraightBeam",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel straight beam between two points\n\nStraightBeam.ByStartPointEndPoint (start: Point, end: Point, orientation: Vector, refAxis: int = 5, crossSectionMirror: bool = false, additionalBeamParameters: Property[] = null): StraightBeam"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "2;\n103;\n50;\n11;\n1;",
      "Id": "7fb9fefa187b49b5bc77724cd944ac93",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a8aae96999f1479a9689ade0188b07b5",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "067b163c533b45899ced19fb3dc7bc4b",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5ab19bfca5b145c18051d083c165be30",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6bed8af7b189419d9062cf09fe80907d",
          "Name": "",
          "Description": "Value of expression at line 4",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "507dc556ea274174baa71a6b6585859c",
          "Name": "",
          "Description": "Value of expression at line 5",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "Point.ByCoordinates(5001,0,0);\nPoint.ByCoordinates(7000,0,0);\nVector.ZAxis();\nPoint.ByCoordinates(6000,0,0);\nVector.XAxis();\nVector.YAxis();",
      "Id": "f3ccab045b79445d928ab7275894fe33",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "5a14c6133ca8400d84c9edb66b30ea52",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ea7ce0a374f147fbb82873767d7fcde6",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f6eecd8c817b4427bc8dc7b926761d66",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5758e34fd34543aca9f6eb09d625b955",
          "Name": "",
          "Description": "Value of expression at line 4",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cd694fd3c5a94f36a46dc8ec02f9f204",
          "Name": "",
          "Description": "Value of expression at line 5",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f40e268a992445c6aaaea9986e65983f",
          "Name": "",
          "Description": "Value of expression at line 6",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Beams.StraightBeam.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,int,bool,AdvanceSteel.Nodes.Property[]",
      "Id": "aad0bc6e3e1142b29a031d03dc399fe2",
      "Inputs": [
        {
          "Id": "439152ed47ae4c2986e92d7c6f3252bb",
          "Name": "start",
          "Description": "Input Start point of Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f544fa9ea11046e6a61e22081afa65f1",
          "Name": "end",
          "Description": "Input End point of Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7778b97305f54127b45e7912e9e7a6c9",
          "Name": "orientation",
          "Description": "Section orientation\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fd1cdb553e2440f0bbb3ccd291abd262",
          "Name": "refAxis",
          "Description": "int\nDefault value : 5",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "edc172761c0b4845b68aef4a107b64e7",
          "Name": "crossSectionMirror",
          "Description": "bool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9d3336dc5c5c42c9b9aea360875d5284",
          "Name": "additionalBeamParameters",
          "Description": "Optional Input Beam Build Properties\n\nProperty[]\nDefault value : null",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d192c69ae8714d5d829d137809d33ba7",
          "Name": "StraightBeam",
          "Description": "StraightBeam",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel straight beam between two points\n\nStraightBeam.ByStartPointEndPoint (start: Point, end: Point, orientation: Vector, refAxis: int = 5, crossSectionMirror: bool = false, additionalBeamParameters: Property[] = null): StraightBeam"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Features.BeamPlaneCut.ByCS@AdvanceSteel.Nodes.SteelDbObject,Autodesk.DesignScript.Geometry.CoordinateSystem,AdvanceSteel.Nodes.Property[]",
      "Id": "a04ea8f962e148aca78d3f4a3b89ca4e",
      "Inputs": [
        {
          "Id": "b70bde55957d463abc9b008fc99a9e7d",
          "Name": "element",
          "Description": "Input Beam\n\nSteelDbObject",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "30c6585b9d0543089fd8b42d307fbbbe",
          "Name": "coordinateSystem",
          "Description": "Input Dynamo CoordinateSytem\n\nCoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b3b24b84600c49b39e4e7e03725341e4",
          "Name": "additionalBeamFeatureParameters",
          "Description": "Optional Input Beam Cut Build Properties\n\nProperty[]\nDefault value : null",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2ba93c91a8514acba0d7adbaefe77633",
          "Name": "BeamPlaneCut",
          "Description": "BeamPlaneCut",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel Beam Plane Cut by Coordinate System\n\nBeamPlaneCut.ByCS (element: SteelDbObject, coordinateSystem: CoordinateSystem, additionalBeamFeatureParameters: Property[] = null): BeamPlaneCut"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Features.BeamPlaneCut.ByStartValue@AdvanceSteel.Nodes.SteelDbObject,double,AdvanceSteel.Nodes.Property[]",
      "Id": "d5de7f8e8a68491f8d75b669b423e075",
      "Inputs": [
        {
          "Id": "65ec7cf931094db88580a6885bd1cb07",
          "Name": "element",
          "Description": "Input Beam\n\nSteelDbObject",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1e967471437e41d9af02c278d7f47a79",
          "Name": "shorteningLength",
          "Description": "Input shortening Value\n\ndouble",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "90cfafc269f64d689cb60a134bffb6e0",
          "Name": "additionalBeamFeatureParameters",
          "Description": "Optional Input Beam Cut Build Properties\n\nProperty[]\nDefault value : null",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "61e93c27188e4f9da27ce53b8e769552",
          "Name": "BeamPlaneCut",
          "Description": "BeamPlaneCut",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel Beam Shorting from the Start of the Beam by a Value\n\nBeamPlaneCut.ByStartValue (element: SteelDbObject, shorteningLength: double, additionalBeamFeatureParameters: Property[] = null): BeamPlaneCut"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Features.BeamPlaneCut.ByStartValue@AdvanceSteel.Nodes.SteelDbObject,double,AdvanceSteel.Nodes.Property[]",
      "Id": "4e60517f366a4e5abebf09a461d66797",
      "Inputs": [
        {
          "Id": "6002a3443cb549c0bb32fae02c5d72c9",
          "Name": "element",
          "Description": "Input Beam\n\nSteelDbObject",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "896849c347244d8fb4c0720d37526bdf",
          "Name": "shorteningLength",
          "Description": "Input shortening Value\n\ndouble",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b864a821ffa3468d89fd5a2e00877ebf",
          "Name": "additionalBeamFeatureParameters",
          "Description": "Optional Input Beam Cut Build Properties\n\nProperty[]\nDefault value : null",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3d99d081ddc543549bf4bfd4644b7c83",
          "Name": "BeamPlaneCut",
          "Description": "BeamPlaneCut",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel Beam Shorting from the Start of the Beam by a Value\n\nBeamPlaneCut.ByStartValue (element: SteelDbObject, shorteningLength: double, additionalBeamFeatureParameters: Property[] = null): BeamPlaneCut"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Features.BeamPlaneCut.ByCS@AdvanceSteel.Nodes.SteelDbObject,Autodesk.DesignScript.Geometry.CoordinateSystem,AdvanceSteel.Nodes.Property[]",
      "Id": "697bb095e47d436e889a184d9e81f00b",
      "Inputs": [
        {
          "Id": "7a5b1825a7d847ee9db52ccaa9920734",
          "Name": "element",
          "Description": "Input Beam\n\nSteelDbObject",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6d2b25df168b4bad9cc592a7fd903b1e",
          "Name": "coordinateSystem",
          "Description": "Input Dynamo CoordinateSytem\n\nCoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "586d8894d39144fa827fb840eb4da7c2",
          "Name": "additionalBeamFeatureParameters",
          "Description": "Optional Input Beam Cut Build Properties\n\nProperty[]\nDefault value : null",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "c6a1ba34aad548aeb646bc7b4d23e6cf",
          "Name": "BeamPlaneCut",
          "Description": "BeamPlaneCut",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel Beam Plane Cut by Coordinate System\n\nBeamPlaneCut.ByCS (element: SteelDbObject, coordinateSystem: CoordinateSystem, additionalBeamFeatureParameters: Property[] = null): BeamPlaneCut"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Features.BeamPolycut.ByLengthWidth@AdvanceSteel.Nodes.SteelDbObject,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,Autodesk.DesignScript.Geometry.Vector,double,double,int,AdvanceSteel.Nodes.Property[]",
      "Id": "0d03dbd0293a4313b0a7d34c3161f856",
      "Inputs": [
        {
          "Id": "dd2dbbdaf74241b6a7b3a79513c0fcf4",
          "Name": "element",
          "Description": "Input Beam\n\nSteelDbObject",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fbac1e5bddd64a3680b729dc31052f0b",
          "Name": "rectangleInsertPoint",
          "Description": "Input Insert Point for Rectangular polycut on Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "271f26a5e60a4d4cbc2c98739f824d56",
          "Name": "normal",
          "Description": "Input normal vector to rectangular polycut\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "81c8f848bae6416f87b2f9c575ec75e8",
          "Name": "lengthVec",
          "Description": "Input vector in the length direction of rectangular polycut\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "505a88154fb44d59adc34177b09e1437",
          "Name": "length",
          "Description": "Input Length of Cut\n\ndouble",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "325c35450e454ab6a70c995811c524c3",
          "Name": "width",
          "Description": "Input depth of Cut\n\ndouble",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a73f53dbdb3b49e2bb79adc54d93ab0b",
          "Name": "corner",
          "Description": "0 - TL, 1 - TR, 2 - BR, 3 - BL, else center\n\nint\nDefault value : -1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2c1bbeed9c0e4b4cbcc061e1dd35d21e",
          "Name": "additionalBeamFeatureParameters",
          "Description": "Optional Input Beam Feature Build Properties\n\nProperty[]\nDefault value : null",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6be3e44edccf4eea827d02c073afa0a5",
          "Name": "BeamPolycut",
          "Description": "BeamPolycut",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel Rectangular Polycut feature by Length and Width\n\nBeamPolycut.ByLengthWidth (element: SteelDbObject, rectangleInsertPoint: Point, normal: Vector, lengthVec: Vector, length: double, width: double, corner: int = -1, additionalBeamFeatureParameters: Property[] = null): BeamPolycut"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Features.BeamPolycut.ByLengthWidth@AdvanceSteel.Nodes.SteelDbObject,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,Autodesk.DesignScript.Geometry.Vector,double,double,int,AdvanceSteel.Nodes.Property[]",
      "Id": "7f43dbbe104c443ea29acd2dc980e7a8",
      "Inputs": [
        {
          "Id": "827e570bcd054e19bb3ec33a14dbcadd",
          "Name": "element",
          "Description": "Input Beam\n\nSteelDbObject",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3441e51e12954309809fad22c07f9ad7",
          "Name": "rectangleInsertPoint",
          "Description": "Input Insert Point for Rectangular polycut on Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4922085619a147dfac093b6515015572",
          "Name": "normal",
          "Description": "Input normal vector to rectangular polycut\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f1d78a279c964644bb4cb9ebb35eba88",
          "Name": "lengthVec",
          "Description": "Input vector in the length direction of rectangular polycut\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "841435df8d6e4514af37c1a68ce5918e",
          "Name": "length",
          "Description": "Input Length of Cut\n\ndouble",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c88044c295364d1dab9469860fcd1290",
          "Name": "width",
          "Description": "Input depth of Cut\n\ndouble",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "39d54274c1c84c84bddf1e517be6d136",
          "Name": "corner",
          "Description": "0 - TL, 1 - TR, 2 - BR, 3 - BL, else center\n\nint\nDefault value : -1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a55893b9ef8e4db48157bb1a168f7b3a",
          "Name": "additionalBeamFeatureParameters",
          "Description": "Optional Input Beam Feature Build Properties\n\nProperty[]\nDefault value : null",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d71c6fa0caab4ae7a9be12c81ed69288",
          "Name": "BeamPolycut",
          "Description": "BeamPolycut",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel Rectangular Polycut feature by Length and Width\n\nBeamPolycut.ByLengthWidth (element: SteelDbObject, rectangleInsertPoint: Point, normal: Vector, lengthVec: Vector, length: double, width: double, corner: int = -1, additionalBeamFeatureParameters: Property[] = null): BeamPolycut"
    }
  ],
  "Connectors": [
    {
      "Start": "e681ea471bb04ebeb415434b2a3f1dd4",
      "End": "10090418f58a4649a8ccc00b4137335e",
      "Id": "f5f4ce5b0602498bb79fd065f9444018"
    },
    {
      "Start": "6b4ec83623de423abbf413fffab2657e",
      "End": "8825e515164d4bdfbf043ebb20a326c0",
      "Id": "1d4e26c23b5b4d36bcc245dbcd659afc"
    },
    {
      "Start": "8a81ab202c4348fb9116faea8e605dde",
      "End": "dca09aaa41834564b2f259aee3c037a0",
      "Id": "bfccc4208a9e4c23bbab3e21c0d27cd2"
    },
    {
      "Start": "944273d75a3a49be8351524bd5ecf48e",
      "End": "26f8db7b2cc44401b2be9b1f3c9d9320",
      "Id": "275642c6a442439ebe381f0f5b7f093e"
    },
    {
      "Start": "48562331105249058fc9af59a46d179a",
      "End": "198478efc5914f87aac804cf112d854e",
      "Id": "faa6419f993745e19a1394dc344d1546"
    },
    {
      "Start": "9388406200eb4610b170de31c33a4836",
      "End": "b425d2fe92b24cc2ab6d6ba2327ea075",
      "Id": "0e1718c4d21042eb91d8bae3b5dce360"
    },
    {
      "Start": "05fd9c6ff4124503867582e87bf0e578",
      "End": "65ec7cf931094db88580a6885bd1cb07",
      "Id": "19ac4d6664634faf8a8aa217e8af85b9"
    },
    {
      "Start": "05fd9c6ff4124503867582e87bf0e578",
      "End": "b70bde55957d463abc9b008fc99a9e7d",
      "Id": "33b344cb062942e4ab79b10b4ee7809c"
    },
    {
      "Start": "7ec4244781a94481a88374cbb51075b9",
      "End": "7a5b1825a7d847ee9db52ccaa9920734",
      "Id": "e13e9ce6c5ea49c09bf86307c69dc837"
    },
    {
      "Start": "7ec4244781a94481a88374cbb51075b9",
      "End": "6002a3443cb549c0bb32fae02c5d72c9",
      "Id": "769def0baf94463aa8c769549ea302f0"
    },
    {
      "Start": "a5b5c312c2b94893a288db354fe1657c",
      "End": "7ac0fba34f124500b1b1f57d60f6cf93",
      "Id": "32e13a2da33b4bc2946816da12a92434"
    },
    {
      "Start": "e120405fc56c436ba5979a72f7644cc2",
      "End": "6d2b25df168b4bad9cc592a7fd903b1e",
      "Id": "2d810f29c44146a38e0ee8eb4fa3dc98"
    },
    {
      "Start": "fe544ccc577945c3bf5ed7997f486e70",
      "End": "30c6585b9d0543089fd8b42d307fbbbe",
      "Id": "034022fd20bb486fb24a5c3ec798b45e"
    },
    {
      "Start": "1fdf33061c1f4fb8b1955ce4af970299",
      "End": "896849c347244d8fb4c0720d37526bdf",
      "Id": "8ec9d5aabc21421cafa9e2ced9265262"
    },
    {
      "Start": "284e9c1814244ef583ca71a8d8218311",
      "End": "1e967471437e41d9af02c278d7f47a79",
      "Id": "e64c4c29dff74bbb8a896bb556debbfc"
    },
    {
      "Start": "52769b394b474d3b9fb2afc26a286a4e",
      "End": "08966f7025534e578f7e71c738432405",
      "Id": "03e35102d7bf467398d65053e6089b1b"
    },
    {
      "Start": "166c69eabe59414d8962bde09576e2d7",
      "End": "d61473af30bd460bb098462808e33701",
      "Id": "15bf88149946444b9495c60642707631"
    },
    {
      "Start": "f99f8617fe744eddbd43f5c9b1cd6325",
      "End": "e9c694c0631941beba9ce2c94d65fe69",
      "Id": "f695794ba35a4fe495ff4042f56dd7ad"
    },
    {
      "Start": "f99f8617fe744eddbd43f5c9b1cd6325",
      "End": "271f26a5e60a4d4cbc2c98739f824d56",
      "Id": "a5f25c2d1d8b4a7c9cf40dfcb2595823"
    },
    {
      "Start": "0a1ae22b8f4949a2a1e9fbd3ecd183e2",
      "End": "fbac1e5bddd64a3680b729dc31052f0b",
      "Id": "68d79e5c306c44b29ba0216cf64bfd5f"
    },
    {
      "Start": "cc5e23a18638401e9051534f9d3b75b0",
      "End": "fd1cdb553e2440f0bbb3ccd291abd262",
      "Id": "80a1ffcc87c84e87bbb98404f210e730"
    },
    {
      "Start": "cc5e23a18638401e9051534f9d3b75b0",
      "End": "236f9a8e630a480e82ffcb53016f5c41",
      "Id": "204b755580d641aeaeee7036b767741c"
    },
    {
      "Start": "e1d6461ab96a4c36ab0b8f164144a2ef",
      "End": "dd2dbbdaf74241b6a7b3a79513c0fcf4",
      "Id": "eb79400fc6e6479b81cb22a1e5686f2e"
    },
    {
      "Start": "067b163c533b45899ced19fb3dc7bc4b",
      "End": "505a88154fb44d59adc34177b09e1437",
      "Id": "4d284da3519d49b08ade879675fa8419"
    },
    {
      "Start": "067b163c533b45899ced19fb3dc7bc4b",
      "End": "841435df8d6e4514af37c1a68ce5918e",
      "Id": "8f364e1d47c04b978983bbe1327fa1c2"
    },
    {
      "Start": "5ab19bfca5b145c18051d083c165be30",
      "End": "325c35450e454ab6a70c995811c524c3",
      "Id": "5ae62156030f4466b826fa07ed790469"
    },
    {
      "Start": "5ab19bfca5b145c18051d083c165be30",
      "End": "c88044c295364d1dab9469860fcd1290",
      "Id": "66d048dacd22410480655f17ba0f0703"
    },
    {
      "Start": "5a14c6133ca8400d84c9edb66b30ea52",
      "End": "439152ed47ae4c2986e92d7c6f3252bb",
      "Id": "91f53a45c7ea492bab5fda9a5eb331cf"
    },
    {
      "Start": "ea7ce0a374f147fbb82873767d7fcde6",
      "End": "f544fa9ea11046e6a61e22081afa65f1",
      "Id": "f043c5804ce946ee99b4f30f984270a9"
    },
    {
      "Start": "f6eecd8c817b4427bc8dc7b926761d66",
      "End": "7778b97305f54127b45e7912e9e7a6c9",
      "Id": "3102da238e374da18ee32d212d5b1cb2"
    },
    {
      "Start": "f6eecd8c817b4427bc8dc7b926761d66",
      "End": "4922085619a147dfac093b6515015572",
      "Id": "5cae91496f154cafb2bd07a44fca5c3e"
    },
    {
      "Start": "5758e34fd34543aca9f6eb09d625b955",
      "End": "3441e51e12954309809fad22c07f9ad7",
      "Id": "95f2351afeb84e17b26be0c41862f198"
    },
    {
      "Start": "cd694fd3c5a94f36a46dc8ec02f9f204",
      "End": "81c8f848bae6416f87b2f9c575ec75e8",
      "Id": "5b0213658ccc4bc199b8d7160d184d7c"
    },
    {
      "Start": "f40e268a992445c6aaaea9986e65983f",
      "End": "f1d78a279c964644bb4cb9ebb35eba88",
      "Id": "ed676fa78b594d789d592a4e6fd5f556"
    },
    {
      "Start": "d192c69ae8714d5d829d137809d33ba7",
      "End": "827e570bcd054e19bb3ec33a14dbcadd",
      "Id": "f8d9f50b7fc24eb0b6974ad857f604cf"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 100.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.5.2.7915",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 4296.6198162662331,
      "EyeY": 3563.1409162434511,
      "EyeZ": 3282.8402385504351,
      "LookX": -1138.3822832735023,
      "LookY": -2038.5399999317651,
      "LookZ": -3767.9772103402929,
      "UpX": -0.07485290483079865,
      "UpY": 0.96592582628907186,
      "UpZ": -0.24775863404969842
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "dfd42be4c2504811ad500ca9cd116013",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 348.18722226620605,
        "Y": 371.62694154841506
      },
      {
        "ShowGeometry": true,
        "Name": "Arc.ByThreePoints",
        "Id": "5419ea8bf2b84c9e8eecde66f2c7c9ce",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 779.4625831884531,
        "Y": 243.0
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "e4dd7650158d4d959d7a03f935d3d716",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 346.91870691116492,
        "Y": 1039.0036765947018
      },
      {
        "ShowGeometry": true,
        "Name": "BentBeam.ByArc",
        "Id": "8478e324a10247059314a826842e6254",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1222.7318190157821,
        "Y": 432.968135994134
      },
      {
        "ShowGeometry": true,
        "Name": "StraightBeam.ByStartPointEndPoint",
        "Id": "9d84acd3b9a44e5ba50417c5d72ce251",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1234.4025277212165,
        "Y": 953.22519474260685
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "632811afea3a41e98058e8d607a1ba7f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 732.82909155310654,
        "Y": 1138.9624130794898
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "88680ee8886d4b249cf25885c2e16ac5",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1223.68524812966,
        "Y": 1300.6085693270054
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "84e3f6fb5b6b4fed997a561a2493e7b0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1146.2237429225597,
        "Y": 154.04088322724624
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "5551985c74ea49c09d12a073601c5a3e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1540.0743990819235,
        "Y": 739.0
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "69fb51abd8cc4fbaa2f2a0f067a3d1ab",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1697.0763367642546,
        "Y": 571.52690946111989
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "437411a14fc9472e8dce741b0a37a2ef",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 564.18182639141673,
        "Y": 1635.1012719759512
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "f9e29ee32fce416cb2fde464e48c5441",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 812.15577108586035,
        "Y": 2079.078214193943
      },
      {
        "ShowGeometry": true,
        "Name": "StraightBeam.ByStartPointEndPoint",
        "Id": "72e5789e1e0c4778bc8686044559bede",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1151.5165071275965,
        "Y": 1911.1177301174846
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "7fb9fefa187b49b5bc77724cd944ac93",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1289.3181597768973,
        "Y": 2166.1307610514832
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "f3ccab045b79445d928ab7275894fe33",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 811.174220067428,
        "Y": 2816.7574143741708
      },
      {
        "ShowGeometry": true,
        "Name": "StraightBeam.ByStartPointEndPoint",
        "Id": "aad0bc6e3e1142b29a031d03dc399fe2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1209.0228515343779,
        "Y": 2410.280045453489
      },
      {
        "ShowGeometry": true,
        "Name": "BeamPlaneCut.ByCS",
        "Id": "a04ea8f962e148aca78d3f4a3b89ca4e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2178.8798321857244,
        "Y": 217.88116406176715
      },
      {
        "ShowGeometry": true,
        "Name": "BeamPlaneCut.ByStartValue",
        "Id": "d5de7f8e8a68491f8d75b669b423e075",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2347.344479429988,
        "Y": 444.98856825814846
      },
      {
        "ShowGeometry": true,
        "Name": "BeamPlaneCut.ByStartValue",
        "Id": "4e60517f366a4e5abebf09a461d66797",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2337.7483919287324,
        "Y": 748.864672464574
      },
      {
        "ShowGeometry": true,
        "Name": "BeamPlaneCut.ByCS",
        "Id": "697bb095e47d436e889a184d9e81f00b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2265.9524057527369,
        "Y": 1151.5487312042412
      },
      {
        "ShowGeometry": true,
        "Name": "BeamPolycut.ByLengthWidth",
        "Id": "0d03dbd0293a4313b0a7d34c3161f856",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2074.7164996187748,
        "Y": 1887.3676023114795
      },
      {
        "ShowGeometry": true,
        "Name": "BeamPolycut.ByLengthWidth",
        "Id": "7f43dbbe104c443ea29acd2dc980e7a8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2293.9355674110161,
        "Y": 2318.43689405158
      }
    ],
    "Annotations": [
      {
        "Id": "d855668f18a74de1bd060a3a7bcc015f",
        "Title": "PROCESS",
        "Nodes": [
          "9860a201583d443cbd3925f2f79c02b1"
        ],
        "Left": 397.7866127772827,
        "Top": -333.96088865533216,
        "Width": 243.0,
        "Height": 97.0,
        "FontSize": 36.0,
        "InitialTop": -280.96088865533216,
        "InitialHeight": 140.0,
        "TextblockHeight": 43.0,
        "Background": "#FFFFAA45"
      },
      {
        "Id": "95751ae1f89442c2826cb50d8c6356e8",
        "Title": "DATA IN",
        "Nodes": [
          "8d3b9fde58d841c8b60402ba9ef5b632"
        ],
        "Left": 397.26891771585861,
        "Top": -434.41777484963927,
        "Width": 244.0,
        "Height": 97.0,
        "FontSize": 36.0,
        "InitialTop": -381.41777484963927,
        "InitialHeight": 140.0,
        "TextblockHeight": 43.0,
        "Background": "#FFFF7BAC"
      },
      {
        "Id": "d683413c43be49dc92c60f0d9aa8308b",
        "Title": "GET",
        "Nodes": [
          "5c1a09ea177e4c77b91d79e6b0e620f6"
        ],
        "Left": 396.81231115143009,
        "Top": -535.92658542435947,
        "Width": 243.0,
        "Height": 97.0,
        "FontSize": 36.0,
        "InitialTop": -482.92658542435947,
        "InitialHeight": 140.0,
        "TextblockHeight": 43.0,
        "Background": "#FFBB87C6"
      },
      {
        "Id": "f14636850f66440e8c6dbc50e5f19705",
        "Title": "GEOM",
        "Nodes": [
          "e70b1fac325047f49bb7502dbced173e"
        ],
        "Left": 396.94595718114988,
        "Top": -232.03213987779077,
        "Width": 244.0,
        "Height": 97.0,
        "FontSize": 36.0,
        "InitialTop": -179.03213987779077,
        "InitialHeight": 140.0,
        "TextblockHeight": 43.0,
        "Background": "#FFFFC999"
      },
      {
        "Id": "539bbb6799d84e879a24cd5cbd2ea0fa",
        "Title": "NOTES - D4C3D",
        "Nodes": [
          "e25df0c2a2064c619714baef6ca43d9f"
        ],
        "Left": 63.546958805192844,
        "Top": -535.25461891331884,
        "Width": 326.0,
        "Height": 414.0,
        "FontSize": 36.0,
        "InitialTop": -482.25461891331884,
        "InitialHeight": 140.0,
        "TextblockHeight": 43.0,
        "Background": "#FF848484"
      },
      {
        "Id": "541c8ad239c74ca797cd2ea6a45ffc1d",
        "Title": "TEMP",
        "Nodes": [
          "ee0a28fa21fd4193b6f6b155a2859d09"
        ],
        "Left": 646.41585832912142,
        "Top": -232.00057569735736,
        "Width": 232.0,
        "Height": 97.0,
        "FontSize": 36.0,
        "InitialTop": -179.00057569735736,
        "InitialHeight": 140.0,
        "TextblockHeight": 43.0,
        "Background": "#FFD8D8D8"
      },
      {
        "Id": "753c943edb6c4a4ebe12d94b6e1feada",
        "Title": "SET",
        "Nodes": [
          "a1af95645ce84b418ec74c8ce99d6e90"
        ],
        "Left": 648.25282264603675,
        "Top": -334.287934170339,
        "Width": 234.0,
        "Height": 97.0,
        "FontSize": 36.0,
        "InitialTop": -281.287934170339,
        "InitialHeight": 140.0,
        "TextblockHeight": 43.0,
        "Background": "#FF71C6A8"
      },
      {
        "Id": "e23e3d26c6f84688905e6875c3225a04",
        "Title": "DATA OUT",
        "Nodes": [
          "548a300efd79407b8c37b9883c19a27e"
        ],
        "Left": 645.42829483220839,
        "Top": -434.49580446720211,
        "Width": 235.0,
        "Height": 97.0,
        "FontSize": 36.0,
        "InitialTop": -381.49580446720211,
        "InitialHeight": 140.0,
        "TextblockHeight": 43.0,
        "Background": "#FF48B9FF"
      },
      {
        "Id": "9709e13eb0654ae4adf5db1fb87ad70e",
        "Title": "CREATE",
        "Nodes": [
          "73579907345a46158f80453da8ab5195"
        ],
        "Left": 644.8151561087202,
        "Top": -536.27099586021882,
        "Width": 236.0,
        "Height": 97.0,
        "FontSize": 36.0,
        "InitialTop": -483.27099586021882,
        "InitialHeight": 140.0,
        "TextblockHeight": 43.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "3e1e523c47ff4d4d8fb67d0a50913119",
        "Title": "GRAPH INFO",
        "Nodes": [
          "8da360e23dc24cb39e1ef1781b9fe253"
        ],
        "Left": 884.70526152047114,
        "Top": -535.11913824920452,
        "Width": 319.0,
        "Height": 400.0,
        "FontSize": 36.0,
        "InitialTop": -482.11913824920452,
        "InitialHeight": 140.0,
        "TextblockHeight": 43.0,
        "Background": "#FF848484"
      },
      {
        "Id": "9860a201583d443cbd3925f2f79c02b1",
        "Title": "Dynamo data manipulation                  ",
        "Nodes": [],
        "Left": 407.7866127772827,
        "Top": -280.96088865533216,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "8d3b9fde58d841c8b60402ba9ef5b632",
        "Title": "Import information / data from others ",
        "Nodes": [],
        "Left": 407.26891771585861,
        "Top": -381.41777484963927,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "5c1a09ea177e4c77b91d79e6b0e620f6",
        "Title": "Get information / data from Civil 3D    ",
        "Nodes": [],
        "Left": 406.81231115143009,
        "Top": -482.92658542435947,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "e70b1fac325047f49bb7502dbced173e",
        "Title": "Dynamo geometry creation                  ",
        "Nodes": [],
        "Left": 406.94595718114988,
        "Top": -179.03213987779077,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "e25df0c2a2064c619714baef6ca43d9f",
        "Title": "DESIGN GRAPH STANDARDS\r\n                                                                                       \r\nAuthor:\t\tJowenn S. Lua\r\nDate Created:\t10 August 2019\r\nDate Updated:\t4 September 2020\r\nVersion:\t\t004\r\n________________________________________________________\r\n\r\nDESIGN GRAPH GUIDELINES\r\n\r\n1. Color code your blocks according to this guide.\r\n\r\n2. Add grouping with name and description.\r\n\r\n3. Add notes to explain each critical node process.\r\n\r\n4. Rename Input / Output / Code Blocks nodes and add suffix to data they carry.\r\n\r\n5. Align nodes to make it neat.\r\n\r\n6. Save the graph as Manual instead of Automatic.\r\n________________________________________________________",
        "Nodes": [],
        "Left": 73.546958805192844,
        "Top": -482.25461891331884,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "ee0a28fa21fd4193b6f6b155a2859d09",
        "Title": "Work in progress / To delete             ",
        "Nodes": [],
        "Left": 656.41585832912142,
        "Top": -179.00057569735736,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "a1af95645ce84b418ec74c8ce99d6e90",
        "Title": "Set or Override Parameter in Civil 3D",
        "Nodes": [],
        "Left": 658.25282264603675,
        "Top": -281.287934170339,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "548a300efd79407b8c37b9883c19a27e",
        "Title": "Export information / data to others   ",
        "Nodes": [],
        "Left": 655.42829483220839,
        "Top": -381.49580446720211,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "73579907345a46158f80453da8ab5195",
        "Title": "Create object in Civil 3D                     ",
        "Nodes": [],
        "Left": 654.8151561087202,
        "Top": -483.27099586021882,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "8da360e23dc24cb39e1ef1781b9fe253",
        "Title": "________________________________________________________\r\n\r\nDynamo Core Ver: \t2.4.1.6394 \r\nDynamo Civil 3D Ver: \t2.4.1.2161\r\n________________________________________________________\r\n\r\nPackage Used: \t\tCivil 3D Toolkit\r\nCustom Nodes Used: \tNone\r\n________________________________________________________\r\n\r\nGraph Function:\r\n1. ???\r\n2. ???\r\n3. ???\r\n________________________________________________________\r\n\r\nCreated By: \t\tJowenn S. Lua\r\nDate Created: \t\tSeptember 2020\r\n\r\nUpdated By:\r\nDate Modified:\r\n ",
        "Nodes": [],
        "Left": 894.70526152047114,
        "Top": -482.11913824920452,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": 249.43434097381464,
    "Y": -51.191444671106126,
    "Zoom": 0.2632910828866461
  }
}