{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Circus",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [
    {
      "Id": "3bb30d391e0c47889321e39b78d25e5b",
      "Name": "Base Radius",
      "Type": "number",
      "Type2": "number",
      "Value": "13000",
      "NumberType": "Double",
      "Description": "Creates a number"
    },
    {
      "Id": "5f2bb3974e524c2387aa36af68b45ed7",
      "Name": "Column Height\r\n",
      "Type": "number",
      "Type2": "number",
      "Value": "3500",
      "NumberType": "Double",
      "Description": "Creates a number"
    },
    {
      "Id": "d7cd6c4d8d4a42dbb8aad53456819ef5",
      "Name": "Divisions",
      "Type": "number",
      "Type2": "number",
      "Value": "20",
      "NumberType": "Double",
      "Description": "Creates a number"
    },
    {
      "Id": "c57a0f13e6294b10b4760f29e084abd6",
      "Name": "Roof Height\r\n",
      "Type": "number",
      "Type2": "number",
      "Value": "4000",
      "NumberType": "Double",
      "Description": "Creates a number"
    },
    {
      "Id": "a15ec09faed544cb8e48d72e7d11dddc",
      "Name": "Top Radius",
      "Type": "number",
      "Type2": "number",
      "Value": "12000",
      "NumberType": "Double",
      "Description": "Creates a number"
    }
  ],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "2e3ec1ac0daa4038ae094cb50334e556",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "3cfecf6576e343dd8b49a57050d2d2da",
          "Name": "centerPoint",
          "Description": "Center point of circle\n\nPoint\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0) (disabled)",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "efad01578589405bb8f74fbe9cf170c2",
          "Name": "radius",
          "Description": "Radius\n\ndouble\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ebad38d64bc14fe88b6d58cf0a7e4629",
          "Name": "Circle",
          "Description": "Circle created with center point and radius",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
      "Replication": "Auto",
      "Description": "Creates a Circle with input center Point and radius in the world XY plane, with world Z as normal.\n\nCircle.ByCenterPointRadius (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1): Circle"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NumberType": "Double",
      "Id": "3bb30d391e0c47889321e39b78d25e5b",
      "NodeType": "NumberInputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "6610dd7c217c411babbb368d0ca044a5",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number",
      "InputValue": 13000.0
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "a77a85f8ad0349e7b01cea2e2f7bc7ee",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "c3cca36d649e402695289d995163d592",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9a9fb9d98f164c47a735749dff6fb945",
          "Name": "direction",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "68cb55434bd34efd91e1424d1b4fa0c5",
          "Name": "Geometry",
          "Description": "Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.Translate@Autodesk.DesignScript.Geometry.Vector",
      "Replication": "Auto",
      "Description": "Translate geometry in the given direction by the vector length\n\nGeometry.Translate (direction: Vector): Geometry"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NumberType": "Double",
      "Id": "5f2bb3974e524c2387aa36af68b45ed7",
      "NodeType": "NumberInputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "694e40882d4b428caf2d7d171101c637",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number",
      "InputValue": 3500.0
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "893f18b2953944bbbff89ec7fca031fb",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "ed992366ef874c848731f4dfbf244366",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c05efc8e6e7245ffa20b6bd2f51fecf7",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0f3d426560ef4974a13e79d33e5930e5",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6118e584ad7c4af7b5a2b50214b322f6",
          "Name": "Vector",
          "Description": "Vector created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Vector by 3 Euclidean coordinates\n\nVector.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Vector"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NumberType": "Double",
      "Id": "d7cd6c4d8d4a42dbb8aad53456819ef5",
      "NodeType": "NumberInputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "f175a781fb9142919afb432d14a727e9",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number",
      "InputValue": 20.0
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "ec3525cb82994fd0aa6a22a507345f08",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "74dca43f089d4e369d6769905c002d1c",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "420614a35b264970964ef1c2185897e9",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.StartPoint",
      "Replication": "Auto",
      "Description": "Get the start Point along the Curve\n\nCurve.StartPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "72dfbc71ff6f499ea306e3c3f44419d6",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "c66921832377474c8259db6ce61d4ae3",
          "Name": "circle",
          "Description": "Autodesk.DesignScript.Geometry.Circle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4ec8527abfb34558b32ae943c02f3a82",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Circle.CenterPoint",
      "Replication": "Auto",
      "Description": "The center of the circle\n\nCircle.CenterPoint: Point"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NumberType": "Double",
      "Id": "c57a0f13e6294b10b4760f29e084abd6",
      "NodeType": "NumberInputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a878f35a592c449fb9cd2d714449f29d",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number",
      "InputValue": 4000.0
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "d5e1df840377476b86494575dc744e4e",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "0969194cb0e248ee86ce1d1283b4706c",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3f10c4f7323b495597cd940ae9cc4742",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1438fd6f2be545ada23d94b5718a45c5",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ba929ca6137b4f348ac05a7afb1a96b3",
          "Name": "Vector",
          "Description": "Vector created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Vector by 3 Euclidean coordinates\n\nVector.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "8c0a80aa8d344ab29ed685f6433906e7",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "84ab95640f934e36a9b7d568d49668f6",
          "Name": "geometry",
          "Description": "Autodesk.DesignScript.Geometry.Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9bb00132b7344d09a94fe7ebf5df060f",
          "Name": "direction",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "42cf690b9922496985850c2a57307571",
          "Name": "Geometry",
          "Description": "Geometry",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Geometry.Translate@Autodesk.DesignScript.Geometry.Vector",
      "Replication": "Auto",
      "Description": "Translate geometry in the given direction by the vector length\n\nGeometry.Translate (direction: Vector): Geometry"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "a316e7f0509b4e2cb60f1db73f62b675",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "b8faa3df714840f3834b5a6f6a70ab3c",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4a5618c6a6424044b9f2e1f18803f4fa",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.EndPoint",
      "Replication": "Auto",
      "Description": "Get the end Point along the Curve\n\nCurve.EndPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "ee9e0666db604195bf0fa12df5881092",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "26f6881c701b44288e18a05392e26168",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ccd53388ba394e91b5a9d4fc1931e660",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8292d1d5e82e491ab5af7fd17f49b902",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f02e73e946c94250a97407a5ae7f3353",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NumberType": "Double",
      "Id": "a15ec09faed544cb8e48d72e7d11dddc",
      "NodeType": "NumberInputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "c7e3edebe193495daf723d06a838eafc",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number",
      "InputValue": 12000.0
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "42cfadcfdd3b4e448a73dfd2271dbeab",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "7b1a97dbf99a4ce6a458f8d925a191f3",
          "Name": "centerPoint",
          "Description": "Center point of circle\n\nPoint\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0) (disabled)",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2b3c2539484446eba7085a1b556e672b",
          "Name": "radius",
          "Description": "Radius\n\ndouble\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d0560b7e88e843b0bf53f57381c47904",
          "Name": "Circle",
          "Description": "Circle created with center point and radius",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
      "Replication": "Auto",
      "Description": "Creates a Circle with input center Point and radius in the world XY plane, with world Z as normal.\n\nCircle.ByCenterPointRadius (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1): Circle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "01f02e6992e84d6a88d8600b67ceb18b",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "6556fe757deb4f91b2b068a0c4f7154d",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "0;"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "2798ac6d48cf4b56bb0200d4324473f3",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "97c72ecbe2794654a2b4276d174da890",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "0;"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "bab007c7d24b4f969fbb475aa85a0718",
      "NodeType": "FunctionNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a97d250aec584f318ebd02505dfeb227",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ZAxis",
      "Replication": "Auto",
      "Description": "Get the canonical Z axis Vector (0,0,1)\n\nVector.ZAxis ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "caabdbe5c81c4d409688fe84243ae54d",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "f1d10e0408ed461193afdea577781356",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "370e058e93bf428681033fec4bf128da",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d3f94bbbf179464ba4e1e189068dcdcd",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double",
      "Replication": "Auto",
      "Description": "Get a Point on the Curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.PointAtParameter (param: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "57a1ca64cb9547fb9b7b3c06d62b563e",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "2decf15a16124c849f04666c3c7e5204",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "0.5;"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "8298d694f2ba457388a377c0009dbe38",
      "NodeType": "FunctionNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "84c1f0a70aa2408fbc704c57278ae871",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ZAxis",
      "Replication": "Auto",
      "Description": "Get the canonical Z axis Vector (0,0,1)\n\nVector.ZAxis ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "f06a054ef9a240319385c22f6c188c21",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "1f7cdfeb06ec46d59e60def93d69eaf1",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f27cd41f1fc640c98d13f01bc70226f5",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.StartPoint",
      "Replication": "Auto",
      "Description": "Get the start Point along the Curve\n\nCurve.StartPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "3e7f064a4a3946ffb4266696adf8ad33",
      "NodeType": "CodeBlockNode",
      "Inputs": [
        {
          "Id": "04d74ca1e1744f8d9469e7e1ca730d8d",
          "Name": "curve",
          "Description": "curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6d7b9d9ef2eb4407884e50fe9b75698f",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "curve;"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "3ffaa897a9174e538d780cfbb6420827",
      "NodeType": "CodeBlockNode",
      "Inputs": [
        {
          "Id": "4cb08dc6f8284e0c80803dd4ee604af1",
          "Name": "x",
          "Description": "x",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "746edfbb81d74d9694e3285cedfa3710",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "x;"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "4ed344d035c642848dacec64f6a85566",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7d4f24e54445473f965324a47b641013",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "0;"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "b719714b357840498f544f54e57de4b4",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "10d986fd016e4758a78833b00775df22",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e0376ba4df754e9da9130eba5b810bfc",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8fa7b35693b54f898a1db8eb3b8b5ddd",
          "Name": "Vector",
          "Description": "A Vector perpendicular to the curve at param",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.NormalAtParameter@double",
      "Replication": "Auto",
      "Description": "Get a Vector perpendicular to the curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.NormalAtParameter (param: double = 0): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "0c336f2e90374a1ca08d8d84613dd082",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "141762f16a364472b11b38078647605f",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "0;"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "51d9feb077774dbca5ee2bacfd59365b",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "80e5c737d353434982e5c5298c754978",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0dbd10e811924de59ceaa38fe6578f34",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.StartPoint",
      "Replication": "Auto",
      "Description": "Get the start Point along the Curve\n\nCurve.StartPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "d97636d57dc840ad815dcdeb357b49f6",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "97a9ec3a29764ecfab28c3b89d4b2da8",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f2a2cbb861014817811c38536a84507c",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.StartPoint",
      "Replication": "Auto",
      "Description": "Get the start Point along the Curve\n\nCurve.StartPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "fb755093ac2e4be48b8b2bfc61d84018",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "0d88ef16ceae436891247a4e9124d9e8",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "42bfb24002d14af280205d001c28b2c7",
          "Name": "points",
          "Description": "The points on the curve at which to split the curve\n\nPoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "493c95c846dc43e4874552c380ac7f0e",
          "Name": "Curve[]",
          "Description": "Curves created from splitting",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.SplitByPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Replication": "Auto",
      "Description": "Split a Curve into multiple pieces at the given points\n\nCurve.SplitByPoints (points: Point[]): Curve[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "cb5df9138e5845e6a26ccbdeea3407b3",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "6fec53673d3c467889f83c579e5730c4",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "17c5a27a731247d8b12de5dfe737549e",
          "Name": "divisions",
          "Description": "Number of divisions\n\nint\nDefault value : 10",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3839493ef210432ab293531f3b3fcb36",
          "Name": "Point[]",
          "Description": "Points spaced equally along length of curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointsAtEqualSegmentLength@int",
      "Replication": "Auto",
      "Description": "Returns points spaced equally along the curve length based on the input number of divisions\n\nCurve.PointsAtEqualSegmentLength (divisions: int = 10): Point[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "21bfc0c20e7c4fd485fa94586bb81f3d",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "718a3838fba845b781ab40ed6032eac8",
          "Name": "start",
          "Description": "Input Start point of Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "acd186e4fdab415985c73d78d91f38fd",
          "Name": "end",
          "Description": "Input End point of Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "193c2aa6609f43cebab4d8786c70e95d",
          "Name": "orientation",
          "Description": "Section orientation\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5848adf27e3d4edc9cb762206d239fdd",
          "Name": "additionalBeamParameters",
          "Description": "Optional Input Beam Build Properties\n\nProperty[]\nDefault value : null",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a0732b210d4245a18fd2ce09f9aa8e35",
          "Name": "straightBeam",
          "Description": "beam",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "AdvanceSteel.Nodes.Beams.StraightBeam.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,AdvanceSteel.Nodes.Property[]",
      "Replication": "Auto",
      "Description": "Create an Advance Steel straight beam between two points\n\nStraightBeam.ByStartPointEndPoint (start: Point, end: Point, orientation: Vector, additionalBeamParameters: Property[] = null): StraightBeam"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "cd0f4212b7e743c1a3798f7ea5f4ead4",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "20fbb92cf7c24a81a0e8bb198628de27",
          "Name": "steelObject",
          "Description": "Advance Steel element\n\nSteelDbObject",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2658816b1ae3433ca997f73c8d707bc6",
          "Name": "AttIdx",
          "Description": "The index of the User attribute. Is a number between 1 and 10\n\nint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3ef11cf305b640ad9a309d99e2ea0220",
          "Name": "value",
          "Description": "Attribute value\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d40bd021debd471d91dfb09158fffc2e",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "AdvanceSteel.Nodes.Util.SteelObject.SetUserAttribute@AdvanceSteel.Nodes.SteelDbObject,int,string",
      "Replication": "Auto",
      "Description": "This node can set User attributes for Advance Steel elements from Dynamo\n\nSteelObject.SetUserAttribute (steelObject: SteelDbObject, AttIdx: int, value: string): void"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "e56c0f6d64434d73922d6ded23a3a25e",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "b3a3732ec28c420bb8af6caecde79707",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "be95411a3cef4b81966f815ce961f941",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "1;\n\"Roof beam\";"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "dee5fb9503c7449a94a5f2cf4e608a72",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "a5bc164708ad46428d449ae8e364daf0",
          "Name": "start",
          "Description": "Start point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bd4412cd99a146c4bf4675f5694feb26",
          "Name": "end",
          "Description": "End point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bface4d35f8a401eb2d1ab6d40ba0b79",
          "Name": "ptOnArc",
          "Description": "Point on arc\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ce2796398c4b49bd803d836623eb3bff",
          "Name": "orientation",
          "Description": "Section orientation\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2543fa0b7d9f4dc08452ac46f0f05774",
          "Name": "additionalBeamParameters",
          "Description": "Optional Input Beam Build Properties\n\nProperty[]\nDefault value : null",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "21a719f559c841bcba1ff4206a1f8f54",
          "Name": "bentBeam",
          "Description": "beam",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "AdvanceSteel.Nodes.Beams.BentBeam.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,AdvanceSteel.Nodes.Property[]",
      "Replication": "Auto",
      "Description": "Create an Advance Steel bent beam between two points and a point on arc\n\nBentBeam.ByStartPointEndPoint (start: Point, end: Point, ptOnArc: Point, orientation: Vector, additionalBeamParameters: Property[] = null): BentBeam"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "1e5e86784a5c4b1dafb1c8ab6e3d0602",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "e8c3ad7409d740c1bfdbed214a9ecf05",
          "Name": "steelObject",
          "Description": "Advance Steel element\n\nSteelDbObject",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fe1e835579d441f48667f82f15dabf71",
          "Name": "AttIdx",
          "Description": "The index of the User attribute. Is a number between 1 and 10\n\nint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "64d930e70ea645da97a10b94377e3d0a",
          "Name": "value",
          "Description": "Attribute value\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "eb46535afa994ff4bfd96dc5e350e6c4",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "AdvanceSteel.Nodes.Util.SteelObject.SetUserAttribute@AdvanceSteel.Nodes.SteelDbObject,int,string",
      "Replication": "Auto",
      "Description": "This node can set User attributes for Advance Steel elements from Dynamo\n\nSteelObject.SetUserAttribute (steelObject: SteelDbObject, AttIdx: int, value: string): void"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "07023133e9104eb79cfe5e6a0935b21c",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a9a9f4eea8114336ae43ae94d6dba79f",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a920f593a6784101b1430807d0c0ebe0",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "1;\n\"Bent beam\";"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "809e5d3484c54b7786c2e48c7057346b",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "0d29f51872b745f98aa44e7a90a808b1",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4ef0cbf796a941e5a04af1c176ceb7e1",
          "Name": "divisions",
          "Description": "Number of divisions\n\nint\nDefault value : 10",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9276cfe7f86f4876ad8326d7fb4ffc19",
          "Name": "Point[]",
          "Description": "Points spaced equally along length of curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointsAtEqualSegmentLength@int",
      "Replication": "Auto",
      "Description": "Returns points spaced equally along the curve length based on the input number of divisions\n\nCurve.PointsAtEqualSegmentLength (divisions: int = 10): Point[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "09a2d9a68c8c4709b7e4990729d22c9f",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "ade08b27ea754b5687fd811102cb4ebf",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1dd5c203665e4ebda3f65b2e8fff265e",
          "Name": "points",
          "Description": "The points on the curve at which to split the curve\n\nPoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9dc17c5af2b840538a53360de7eb6932",
          "Name": "Curve[]",
          "Description": "Curves created from splitting",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.SplitByPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Replication": "Auto",
      "Description": "Split a Curve into multiple pieces at the given points\n\nCurve.SplitByPoints (points: Point[]): Curve[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "0fbd09c3a4364f33b2d7968c19d25d99",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "c74f4535ecdb47f3a46e5be53f5eb56f",
          "Name": "start",
          "Description": "Input Start point of Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ba70340f435f4f688a9ef6a4007bda49",
          "Name": "end",
          "Description": "Input End point of Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "16e1ecd45a3440a5ac0c1b04a43ec4f0",
          "Name": "orientation",
          "Description": "Section orientation\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2dac3199285041aebc2f2a4d86fcff81",
          "Name": "additionalBeamParameters",
          "Description": "Optional Input Beam Build Properties\n\nProperty[]\nDefault value : null",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b6eb8860a3c740f4b57969608d9e8833",
          "Name": "straightBeam",
          "Description": "beam",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "AdvanceSteel.Nodes.Beams.StraightBeam.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,AdvanceSteel.Nodes.Property[]",
      "Replication": "Auto",
      "Description": "Create an Advance Steel straight beam between two points\n\nStraightBeam.ByStartPointEndPoint (start: Point, end: Point, orientation: Vector, additionalBeamParameters: Property[] = null): StraightBeam"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "3af1ed8964b7468db5eef5c33fe71f15",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "9879b6947906426f9798186f1d6a7727",
          "Name": "steelObject",
          "Description": "Advance Steel element\n\nSteelDbObject",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "73129d0bbc79479684070ee732262927",
          "Name": "AttIdx",
          "Description": "The index of the User attribute. Is a number between 1 and 10\n\nint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "63a67403ef124acf80eaf47e1dfa162f",
          "Name": "value",
          "Description": "Attribute value\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ddf6d46eb11d4e20ba601a08228e25f9",
          "Name": "void",
          "Description": "void",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "AdvanceSteel.Nodes.Util.SteelObject.SetUserAttribute@AdvanceSteel.Nodes.SteelDbObject,int,string",
      "Replication": "Auto",
      "Description": "This node can set User attributes for Advance Steel elements from Dynamo\n\nSteelObject.SetUserAttribute (steelObject: SteelDbObject, AttIdx: int, value: string): void"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "76d3354714f54fafa46fda9b1a264a1b",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "5ffcfb9b7b2f44e5902566c9cf77b293",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2210ff4ec8514dd4aff67f130607995c",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "1;\n\"Column\";"
    }
  ],
  "Connectors": [
    {
      "Start": "ebad38d64bc14fe88b6d58cf0a7e4629",
      "End": "ade08b27ea754b5687fd811102cb4ebf",
      "Id": "449e912352f14d03b163721e91582f7f",
      "IsHidden": "False"
    },
    {
      "Start": "ebad38d64bc14fe88b6d58cf0a7e4629",
      "End": "0d29f51872b745f98aa44e7a90a808b1",
      "Id": "1e716babd1fa437e9b9040a9569584f4",
      "IsHidden": "False"
    },
    {
      "Start": "6610dd7c217c411babbb368d0ca044a5",
      "End": "efad01578589405bb8f74fbe9cf170c2",
      "Id": "1b38f2b429d043b7ab1bd9b7164b1805",
      "IsHidden": "False"
    },
    {
      "Start": "68cb55434bd34efd91e1424d1b4fa0c5",
      "End": "c66921832377474c8259db6ce61d4ae3",
      "Id": "c7572aa1a7a247808ba602e31d956f72",
      "IsHidden": "False"
    },
    {
      "Start": "68cb55434bd34efd91e1424d1b4fa0c5",
      "End": "0d88ef16ceae436891247a4e9124d9e8",
      "Id": "a2382c7fed1b406b8d8d3c10e89bb6d7",
      "IsHidden": "False"
    },
    {
      "Start": "68cb55434bd34efd91e1424d1b4fa0c5",
      "End": "6fec53673d3c467889f83c579e5730c4",
      "Id": "00dc5f82ccd6489cbbfdcdc85d4ab968",
      "IsHidden": "False"
    },
    {
      "Start": "694e40882d4b428caf2d7d171101c637",
      "End": "0f3d426560ef4974a13e79d33e5930e5",
      "Id": "f035b7f3d82843f189c8bf9dba8c17f8",
      "IsHidden": "False"
    },
    {
      "Start": "6118e584ad7c4af7b5a2b50214b322f6",
      "End": "9a9fb9d98f164c47a735749dff6fb945",
      "Id": "0e5e477b75734ad9be06cb9690a9e4da",
      "IsHidden": "False"
    },
    {
      "Start": "f175a781fb9142919afb432d14a727e9",
      "End": "4cb08dc6f8284e0c80803dd4ee604af1",
      "Id": "4df2ab2a15f8436b9b7799fc2f79f199",
      "IsHidden": "False"
    },
    {
      "Start": "420614a35b264970964ef1c2185897e9",
      "End": "a5bc164708ad46428d449ae8e364daf0",
      "Id": "824bb5d7ec4f47249eab036c422b7c6f",
      "IsHidden": "False"
    },
    {
      "Start": "4ec8527abfb34558b32ae943c02f3a82",
      "End": "84ab95640f934e36a9b7d568d49668f6",
      "Id": "dbe6dc4e6cda4d90b78297c1ae671180",
      "IsHidden": "False"
    },
    {
      "Start": "a878f35a592c449fb9cd2d714449f29d",
      "End": "1438fd6f2be545ada23d94b5718a45c5",
      "Id": "0e9534feef1c4b5bb7add0045f074d50",
      "IsHidden": "False"
    },
    {
      "Start": "ba929ca6137b4f348ac05a7afb1a96b3",
      "End": "9bb00132b7344d09a94fe7ebf5df060f",
      "Id": "d498f56ced7444949654978c8932b686",
      "IsHidden": "False"
    },
    {
      "Start": "42cf690b9922496985850c2a57307571",
      "End": "acd186e4fdab415985c73d78d91f38fd",
      "Id": "9ea987776d2c4396b4e34ebb36f341b6",
      "IsHidden": "False"
    },
    {
      "Start": "4a5618c6a6424044b9f2e1f18803f4fa",
      "End": "bd4412cd99a146c4bf4675f5694feb26",
      "Id": "3678b14a44c149c18a0b104f47bfaca3",
      "IsHidden": "False"
    },
    {
      "Start": "f02e73e946c94250a97407a5ae7f3353",
      "End": "7b1a97dbf99a4ce6a458f8d925a191f3",
      "Id": "347b4e6af5fe4172a697365a79773793",
      "IsHidden": "False"
    },
    {
      "Start": "f02e73e946c94250a97407a5ae7f3353",
      "End": "3cfecf6576e343dd8b49a57050d2d2da",
      "Id": "3096baacb17b4457a44518deef11e429",
      "IsHidden": "False"
    },
    {
      "Start": "c7e3edebe193495daf723d06a838eafc",
      "End": "2b3c2539484446eba7085a1b556e672b",
      "Id": "0a38dd5b14214a12ab03c30a229f288a",
      "IsHidden": "False"
    },
    {
      "Start": "d0560b7e88e843b0bf53f57381c47904",
      "End": "c3cca36d649e402695289d995163d592",
      "Id": "a22706767a624d098a24bcaa40a63e10",
      "IsHidden": "False"
    },
    {
      "Start": "6556fe757deb4f91b2b068a0c4f7154d",
      "End": "ccd53388ba394e91b5a9d4fc1931e660",
      "Id": "3ed7994f97ab4bbe9ca3902f2e712615",
      "IsHidden": "False"
    },
    {
      "Start": "97c72ecbe2794654a2b4276d174da890",
      "End": "8292d1d5e82e491ab5af7fd17f49b902",
      "Id": "b3d6cf20c86e454798cff17a3fc56854",
      "IsHidden": "False"
    },
    {
      "Start": "a97d250aec584f318ebd02505dfeb227",
      "End": "ce2796398c4b49bd803d836623eb3bff",
      "Id": "9b8fbc3f39a649a4bfc3d930961577be",
      "IsHidden": "False"
    },
    {
      "Start": "d3f94bbbf179464ba4e1e189068dcdcd",
      "End": "bface4d35f8a401eb2d1ab6d40ba0b79",
      "Id": "2eb8486a9ee844fe9b33f8511c896479",
      "IsHidden": "False"
    },
    {
      "Start": "2decf15a16124c849f04666c3c7e5204",
      "End": "370e058e93bf428681033fec4bf128da",
      "Id": "8cf73b9122264639be740e1be6b8e162",
      "IsHidden": "False"
    },
    {
      "Start": "84c1f0a70aa2408fbc704c57278ae871",
      "End": "193c2aa6609f43cebab4d8786c70e95d",
      "Id": "e9514f75d24a44df9c5feb677ff7d6c7",
      "IsHidden": "False"
    },
    {
      "Start": "f27cd41f1fc640c98d13f01bc70226f5",
      "End": "718a3838fba845b781ab40ed6032eac8",
      "Id": "9e9e76590241412b96cf50b16bf844c6",
      "IsHidden": "False"
    },
    {
      "Start": "6d7b9d9ef2eb4407884e50fe9b75698f",
      "End": "74dca43f089d4e369d6769905c002d1c",
      "Id": "a1b3e45c678847159e97f1fa291dc909",
      "IsHidden": "False"
    },
    {
      "Start": "6d7b9d9ef2eb4407884e50fe9b75698f",
      "End": "b8faa3df714840f3834b5a6f6a70ab3c",
      "Id": "420d826cfc434fe68fd0430c06610a19",
      "IsHidden": "False"
    },
    {
      "Start": "6d7b9d9ef2eb4407884e50fe9b75698f",
      "End": "f1d10e0408ed461193afdea577781356",
      "Id": "a9c87a05280646b6b8d8b3c2012241dc",
      "IsHidden": "False"
    },
    {
      "Start": "746edfbb81d74d9694e3285cedfa3710",
      "End": "17c5a27a731247d8b12de5dfe737549e",
      "Id": "4c2c555724e341eb918b8cfbf6933f3e",
      "IsHidden": "False"
    },
    {
      "Start": "746edfbb81d74d9694e3285cedfa3710",
      "End": "4ef0cbf796a941e5a04af1c176ceb7e1",
      "Id": "e566ceee90d94d21b70129a7ec2d3ec2",
      "IsHidden": "False"
    },
    {
      "Start": "7d4f24e54445473f965324a47b641013",
      "End": "26f6881c701b44288e18a05392e26168",
      "Id": "0a5e0bfbc4a24d62aa3c1d353aca7fc5",
      "IsHidden": "False"
    },
    {
      "Start": "8fa7b35693b54f898a1db8eb3b8b5ddd",
      "End": "16e1ecd45a3440a5ac0c1b04a43ec4f0",
      "Id": "84dd7fe6e56f493e8e2de199e5054658",
      "IsHidden": "False"
    },
    {
      "Start": "141762f16a364472b11b38078647605f",
      "End": "e0376ba4df754e9da9130eba5b810bfc",
      "Id": "474e83eb4d604265b95dada6a3e145de",
      "IsHidden": "False"
    },
    {
      "Start": "0dbd10e811924de59ceaa38fe6578f34",
      "End": "ba70340f435f4f688a9ef6a4007bda49",
      "Id": "b03c7917c6024733b1730f9e05b2f79a",
      "IsHidden": "False"
    },
    {
      "Start": "f2a2cbb861014817811c38536a84507c",
      "End": "c74f4535ecdb47f3a46e5be53f5eb56f",
      "Id": "25aa671b29c34bc298b0c25b9bd83e6c",
      "IsHidden": "False"
    },
    {
      "Start": "493c95c846dc43e4874552c380ac7f0e",
      "End": "1f7cdfeb06ec46d59e60def93d69eaf1",
      "Id": "5ea299533f214518a60020b8727e0ae5",
      "IsHidden": "False"
    },
    {
      "Start": "493c95c846dc43e4874552c380ac7f0e",
      "End": "04d74ca1e1744f8d9469e7e1ca730d8d",
      "Id": "260ed8089b3549ec98b67f769cf889d1",
      "IsHidden": "False"
    },
    {
      "Start": "493c95c846dc43e4874552c380ac7f0e",
      "End": "80e5c737d353434982e5c5298c754978",
      "Id": "59645b719a4a4180b172ac7e4ed9edca",
      "IsHidden": "False"
    },
    {
      "Start": "3839493ef210432ab293531f3b3fcb36",
      "End": "42bfb24002d14af280205d001c28b2c7",
      "Id": "1e5fa2c1fef24e77830d81fd8dc7260d",
      "IsHidden": "False"
    },
    {
      "Start": "a0732b210d4245a18fd2ce09f9aa8e35",
      "End": "20fbb92cf7c24a81a0e8bb198628de27",
      "Id": "94289912115c40bf95839d38a7af4ede",
      "IsHidden": "False"
    },
    {
      "Start": "b3a3732ec28c420bb8af6caecde79707",
      "End": "2658816b1ae3433ca997f73c8d707bc6",
      "Id": "b9ec50aedf944aabbc0a96c9760fb5f2",
      "IsHidden": "False"
    },
    {
      "Start": "be95411a3cef4b81966f815ce961f941",
      "End": "3ef11cf305b640ad9a309d99e2ea0220",
      "Id": "653e5f867122445eb68b512d99db6ae5",
      "IsHidden": "False"
    },
    {
      "Start": "21a719f559c841bcba1ff4206a1f8f54",
      "End": "e8c3ad7409d740c1bfdbed214a9ecf05",
      "Id": "d1a484bd0a214ae480eee3153dbc1605",
      "IsHidden": "False"
    },
    {
      "Start": "a9a9f4eea8114336ae43ae94d6dba79f",
      "End": "fe1e835579d441f48667f82f15dabf71",
      "Id": "d2cc17d0861c4c7288b50b88926d258a",
      "IsHidden": "False"
    },
    {
      "Start": "a920f593a6784101b1430807d0c0ebe0",
      "End": "64d930e70ea645da97a10b94377e3d0a",
      "Id": "a5edb613091b4f0681c00888a44cd172",
      "IsHidden": "False"
    },
    {
      "Start": "9276cfe7f86f4876ad8326d7fb4ffc19",
      "End": "1dd5c203665e4ebda3f65b2e8fff265e",
      "Id": "09045ac519b5488fbf2791a6b1ba0ef1",
      "IsHidden": "False"
    },
    {
      "Start": "9dc17c5af2b840538a53360de7eb6932",
      "End": "97a9ec3a29764ecfab28c3b89d4b2da8",
      "Id": "55a8783e4db9447bba2c812701eac18c",
      "IsHidden": "False"
    },
    {
      "Start": "9dc17c5af2b840538a53360de7eb6932",
      "End": "10d986fd016e4758a78833b00775df22",
      "Id": "4991d49d37c74fdba639674264098cee",
      "IsHidden": "False"
    },
    {
      "Start": "b6eb8860a3c740f4b57969608d9e8833",
      "End": "9879b6947906426f9798186f1d6a7727",
      "Id": "549b171ec86e4184960af92f9c55fa6a",
      "IsHidden": "False"
    },
    {
      "Start": "5ffcfb9b7b2f44e5902566c9cf77b293",
      "End": "73129d0bbc79479684070ee732262927",
      "Id": "9f46052d1f4541ebadbd9503c579dc82",
      "IsHidden": "False"
    },
    {
      "Start": "2210ff4ec8514dd4aff67f130607995c",
      "End": "63a67403ef124acf80eaf47e1dfa162f",
      "Id": "d11dd33f855343aea80a71aa05514c6f",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "EnableLegacyPolyCurveBehavior": true,
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.13",
      "Data": {}
    }
  ],
  "Author": "Autodesk",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [
    {
      "NodeId": "21bfc0c2-0e7c-4fd4-85fa-94586bb81f3d",
      "Binding": {
        "ByStartPointEndPoint_InClassDecl-1_InFunctionScope-1_Instance0_21bfc0c2-0e7c-4fd4-85fa-94586bb81f3d": "H4sIAAAAAAAAClXNoQ6AIBhF4Xf5s8U55zTC1ZdgBDaoFmmMd9dZ9LRz0heaneWqJSvVZFtolt8w56wP3wl3/M+PuAk34xbcioPn4Xl4gid4gid4gid4gid4++PFHm+d1ZbrKgEAAA=="
      }
    },
    {
      "NodeId": "dee5fb95-03c7-449a-94a5-f2cf4e608a72",
      "Binding": {
        "ByStartPointEndPoint_InClassDecl-1_InFunctionScope-1_Instance0_dee5fb95-03c7-449a-94a5-f2cf4e608a72": "H4sIAAAAAAAAClXNMQqAMBAF0btsbSMiEru/BC8RUgS0tTFdyN0VG51upnqp2Xlc9dhjqcXW1Gx/w8Jkffhuxi24gHNcxG3/04iDJ3iCJ3iCJ3iC5/AcnsNzeP54uecbvfLW5ioBAAA="
      }
    },
    {
      "NodeId": "0fbd09c3-a436-4f33-b2d7-968c19d25d99",
      "Binding": {
        "ByStartPointEndPoint_InClassDecl-1_InFunctionScope-1_Instance0_0fbd09c3-a436-4f33-b2d7-968c19d25d99": "H4sIAAAAAAAAClXNIQ6AMBAAwb+cRtyFEAKSlPtEg2jSWgx1Tf8OwcC6XTWxyVmuWnJINckam+Q3ZB+lD99NuBm34DZcwPn/3HDwHJ7Dc3gOz+E5PFOAphBNQZrCNH3Qox832IHW9i8BAAA="
      }
    }
  ],
  "View": {
    "Dynamo": {
      "ScaleFactor": 100.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "3.4.2.7731",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "_Background Preview",
      "EyeX": 48912.47180745139,
      "EyeY": 68295.15215276618,
      "EyeZ": -27572.721611426616,
      "LookX": -48912.47180745139,
      "LookY": -64545.15215276619,
      "LookZ": 27572.721611426616,
      "UpX": -0.519385039806366,
      "UpY": 0.8028174638748169,
      "UpZ": 0.2927854061126709
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Id": "2e3ec1ac0daa4038ae094cb50334e556",
        "Name": "Circle.ByCenterPointRadius",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 543.1235887485498,
        "Y": 716.5871050196225
      },
      {
        "Id": "3bb30d391e0c47889321e39b78d25e5b",
        "Name": "Base Radius",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -1077.243054949404,
        "Y": 733.682173565126
      },
      {
        "Id": "a77a85f8ad0349e7b01cea2e2f7bc7ee",
        "Name": "Geometry.Translate",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 80.08218271760529,
        "Y": 210.69277875468435
      },
      {
        "Id": "5f2bb3974e524c2387aa36af68b45ed7",
        "Name": "Column Height\r\n",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -1077.243054949404,
        "Y": 417.89274284473
      },
      {
        "Id": "893f18b2953944bbbff89ec7fca031fb",
        "Name": "Vector.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": -295.9178172823947,
        "Y": 322.69277875468435
      },
      {
        "Id": "d7cd6c4d8d4a42dbb8aad53456819ef5",
        "Name": "Divisions",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -1077.243054949404,
        "Y": 583.287458204928
      },
      {
        "Id": "ec3525cb82994fd0aa6a22a507345f08",
        "Name": "Curve.StartPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1612.3313240779635,
        "Y": 42.73669912269969
      },
      {
        "Id": "72dfbc71ff6f499ea306e3c3f44419d6",
        "Name": "Circle.CenterPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1552.3860887751043,
        "Y": -620.8523927204329
      },
      {
        "Id": "c57a0f13e6294b10b4760f29e084abd6",
        "Name": "Roof Height\r\n",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1290.3860887751043,
        "Y": -392.85239272043293
      },
      {
        "Id": "d5e1df840377476b86494575dc744e4e",
        "Name": "Vector.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1552.3860887751043,
        "Y": -460.85239272043293
      },
      {
        "Id": "8c0a80aa8d344ab29ed685f6433906e7",
        "Name": "Geometry.Translate",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1885.3860887751043,
        "Y": -557.8523927204329
      },
      {
        "Id": "a316e7f0509b4e2cb60f1db73f62b675",
        "Name": "Curve.EndPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1612.3313240779635,
        "Y": 201.7366991226997
      },
      {
        "Id": "ee9e0666db604195bf0fa12df5881092",
        "Name": "Point.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": -681.0721458711353,
        "Y": -30.814260284736292
      },
      {
        "Id": "a15ec09faed544cb8e48d72e7d11dddc",
        "Name": "Top Radius",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -1077.243054949404,
        "Y": 267.498027484532
      },
      {
        "Id": "42cfadcfdd3b4e448a73dfd2271dbeab",
        "Name": "Circle.ByCenterPointRadius",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": -295.9178172823947,
        "Y": 132.69277875468435
      },
      {
        "Id": "01f02e6992e84d6a88d8600b67ceb18b",
        "Name": "Y Coordinate",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -1077.243054949404,
        "Y": -33.291403235863754
      },
      {
        "Id": "2798ac6d48cf4b56bb0200d4324473f3",
        "Name": "Z Coordinate",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -1077.243054949404,
        "Y": 117.10331212433397
      },
      {
        "Id": "bab007c7d24b4f969fbb475aa85a0718",
        "Name": "Vector.ZAxis",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1612.3313240779635,
        "Y": 549.7366991226997
      },
      {
        "Id": "caabdbe5c81c4d409688fe84243ae54d",
        "Name": "Curve.PointAtParameter",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1612.3313240779635,
        "Y": 360.7366991226997
      },
      {
        "Id": "57a1ca64cb9547fb9b7b3c06d62b563e",
        "Name": "Middle of Curve",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1322.3313240779635,
        "Y": 394.5641991226997
      },
      {
        "Id": "8298d694f2ba457388a377c0009dbe38",
        "Name": "Vector.ZAxis",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1885.3860887751043,
        "Y": -367.85239272043293
      },
      {
        "Id": "f06a054ef9a240319385c22f6c188c21",
        "Name": "Curve.StartPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1885.3860887751043,
        "Y": -717.8523927204329
      },
      {
        "Id": "3e7f064a4a3946ffb4266696adf8ad33",
        "Name": "Bent Beams",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1322.3313240779635,
        "Y": 201.56419912269968
      },
      {
        "Id": "3ffaa897a9174e538d780cfbb6420827",
        "Name": "Divisions",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": -18.742785678182145,
        "Y": 471.4065888110904
      },
      {
        "Id": "4ed344d035c642848dacec64f6a85566",
        "Name": "X Coordinate",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -1077.243054949404,
        "Y": -188.68611859606153
      },
      {
        "Id": "b719714b357840498f544f54e57de4b4",
        "Name": "Curve.NormalAtParameter",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 2053.401975525605,
        "Y": 1237.16492345811
      },
      {
        "Id": "0c336f2e90374a1ca08d8d84613dd082",
        "Name": "Code Block",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1733.401975525605,
        "Y": 1270.99242345811
      },
      {
        "Id": "51d9feb077774dbca5ee2bacfd59365b",
        "Name": "Curve.StartPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 2053.401975525605,
        "Y": 1077.16492345811
      },
      {
        "Id": "d97636d57dc840ad815dcdeb357b49f6",
        "Name": "Curve.StartPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 2053.401975525605,
        "Y": 917.16492345811
      },
      {
        "Id": "fb755093ac2e4be48b8b2bfc61d84018",
        "Name": "Curve.SplitByPoints",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 861.0821827176053,
        "Y": 210.69277875468435
      },
      {
        "Id": "cb5df9138e5845e6a26ccbdeea3407b3",
        "Name": "Curve.PointsAtEqualSegmentLength",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 417.0821827176053,
        "Y": 244.69277875468435
      },
      {
        "Id": "21bfc0c20e7c4fd485fa94586bb81f3d",
        "Name": "StraightBeam.ByStartPointEndPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 2222.3860887751043,
        "Y": -581.8523927204329
      },
      {
        "Id": "cd0f4212b7e743c1a3798f7ea5f4ead4",
        "Name": "SteelObject.SetUserAttribute",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 2680.3860887751043,
        "Y": -478.85239272043293
      },
      {
        "Id": "e56c0f6d64434d73922d6ded23a3a25e",
        "Name": "Code Block",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 2222.3860887751043,
        "Y": -333.19739272043296
      },
      {
        "Id": "dee5fb9503c7449a94a5f2cf4e608a72",
        "Name": "BentBeam.ByStartPointEndPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 1964.3313240779635,
        "Y": 237.7366991226997
      },
      {
        "Id": "1e5e86784a5c4b1dafb1c8ab6e3d0602",
        "Name": "SteelObject.SetUserAttribute",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 2403.3313240779635,
        "Y": 357.7366991226997
      },
      {
        "Id": "07023133e9104eb79cfe5e6a0935b21c",
        "Name": "Code Block",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1964.3313240779635,
        "Y": 520.3916991226997
      },
      {
        "Id": "809e5d3484c54b7786c2e48c7057346b",
        "Name": "Curve.PointsAtEqualSegmentLength",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1289.401975525605,
        "Y": 1111.16492345811
      },
      {
        "Id": "09a2d9a68c8c4709b7e4990729d22c9f",
        "Name": "Curve.SplitByPoints",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 1733.401975525605,
        "Y": 1077.16492345811
      },
      {
        "Id": "0fbd09c3a4364f33b2d7968c19d25d99",
        "Name": "StraightBeam.ByStartPointEndPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 2421.401975525605,
        "Y": 1043.16492345811
      },
      {
        "Id": "3af1ed8964b7468db5eef5c33fe71f15",
        "Name": "SteelObject.SetUserAttribute",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 2879.401975525605,
        "Y": 1146.16492345811
      },
      {
        "Id": "76d3354714f54fafa46fda9b1a264a1b",
        "Name": "Code Block",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": false,
        "X": 2421.401975525605,
        "Y": 1291.81992345811
      }
    ],
    "Annotations": [
      {
        "Id": "9e48f86d31c54082958bea4a0e60ad88",
        "Title": "Input values",
        "DescriptionText": null,
        "IsExpanded": true,
        "WidthAdjustment": 0.0,
        "HeightAdjustment": 0.0,
        "Nodes": [
          "3bb30d391e0c47889321e39b78d25e5b",
          "5f2bb3974e524c2387aa36af68b45ed7",
          "d7cd6c4d8d4a42dbb8aad53456819ef5",
          "a15ec09faed544cb8e48d72e7d11dddc",
          "01f02e6992e84d6a88d8600b67ceb18b",
          "2798ac6d48cf4b56bb0200d4324473f3",
          "4ed344d035c642848dacec64f6a85566"
        ],
        "HasNestedGroups": false,
        "Left": -1087.243054949404,
        "Top": -238.68611859606153,
        "Width": 204.0,
        "Height": 1104.3682921611876,
        "FontSize": 14.0,
        "GroupStyleId": "00000000-0000-0000-0000-000000000000",
        "InitialTop": -188.68611859606153,
        "InitialHeight": 1067.3682921611876,
        "TextblockHeight": 40.0,
        "Background": "#FFFF7BAC"
      },
      {
        "Id": "f941d9af123843e78706a71b9861c8c6",
        "Title": "Roof Beams",
        "DescriptionText": null,
        "IsExpanded": true,
        "WidthAdjustment": 0.0,
        "HeightAdjustment": 0.0,
        "Nodes": [
          "72dfbc71ff6f499ea306e3c3f44419d6",
          "c57a0f13e6294b10b4760f29e084abd6",
          "d5e1df840377476b86494575dc744e4e",
          "8c0a80aa8d344ab29ed685f6433906e7",
          "8298d694f2ba457388a377c0009dbe38",
          "f06a054ef9a240319385c22f6c188c21",
          "21bfc0c20e7c4fd485fa94586bb81f3d",
          "cd0f4212b7e743c1a3798f7ea5f4ead4",
          "e56c0f6d64434d73922d6ded23a3a25e"
        ],
        "HasNestedGroups": false,
        "Left": 1280.3860887751043,
        "Top": -767.8523927204329,
        "Width": 1700.0,
        "Height": 588.655,
        "FontSize": 14.0,
        "GroupStyleId": "00000000-0000-0000-0000-000000000000",
        "InitialTop": -717.8523927204329,
        "InitialHeight": 529.655,
        "TextblockHeight": 40.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "dc35a958a6754a24a5e400bfd9015819",
        "Title": "Bent Beams",
        "DescriptionText": null,
        "IsExpanded": true,
        "WidthAdjustment": 0.0,
        "HeightAdjustment": 0.0,
        "Nodes": [
          "ec3525cb82994fd0aa6a22a507345f08",
          "a316e7f0509b4e2cb60f1db73f62b675",
          "bab007c7d24b4f969fbb475aa85a0718",
          "caabdbe5c81c4d409688fe84243ae54d",
          "57a1ca64cb9547fb9b7b3c06d62b563e",
          "3e7f064a4a3946ffb4266696adf8ad33",
          "dee5fb9503c7449a94a5f2cf4e608a72",
          "1e5e86784a5c4b1dafb1c8ab6e3d0602",
          "07023133e9104eb79cfe5e6a0935b21c"
        ],
        "HasNestedGroups": false,
        "Left": 1312.3313240779635,
        "Top": -7.26330087730031,
        "Width": 1391.0,
        "Height": 701.0,
        "FontSize": 14.0,
        "GroupStyleId": "00000000-0000-0000-0000-000000000000",
        "InitialTop": 42.73669912269969,
        "InitialHeight": 652.0,
        "TextblockHeight": 40.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "3fc1d4fd81be4296a7f2886351c4ac04",
        "Title": "Columns",
        "DescriptionText": null,
        "IsExpanded": true,
        "WidthAdjustment": 0.0,
        "HeightAdjustment": 0.0,
        "Nodes": [
          "b719714b357840498f544f54e57de4b4",
          "0c336f2e90374a1ca08d8d84613dd082",
          "51d9feb077774dbca5ee2bacfd59365b",
          "d97636d57dc840ad815dcdeb357b49f6",
          "809e5d3484c54b7786c2e48c7057346b",
          "09a2d9a68c8c4709b7e4990729d22c9f",
          "0fbd09c3a4364f33b2d7968c19d25d99",
          "3af1ed8964b7468db5eef5c33fe71f15",
          "76d3354714f54fafa46fda9b1a264a1b"
        ],
        "HasNestedGroups": false,
        "Left": 1279.401975525605,
        "Top": 867.16492345811,
        "Width": 1900.0,
        "Height": 578.655,
        "FontSize": 14.0,
        "GroupStyleId": "00000000-0000-0000-0000-000000000000",
        "InitialTop": 917.16492345811,
        "InitialHeight": 519.655,
        "TextblockHeight": 40.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": 829.046745656512,
    "Y": 248.96864141895844,
    "Zoom": 0.6737233538541779
  }
}