{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Welds",
  "ElementResolver": {
    "ResolutionMap": {
      "Vector": {
        "Key": "Autodesk.DesignScript.Geometry.Vector",
        "Value": "ProtoGeometry.dll"
      },
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Rectangle": {
        "Key": "Autodesk.DesignScript.Geometry.Rectangle",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "Point.ByCoordinates(0,0,0);\nPoint.ByCoordinates(2001,0,0);\nVector.ZAxis();\n\"Horizontal_Beam\";",
      "Id": "0d7d0194e1cb40818e02d464be6776dc",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "1150e60fdb91433f94c7552ee6658d88",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "459e7b27d8f94fe993a9793ed4ea0765",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "db0baf1428c6478b83518917ef36fba4",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9991f2ec1b10434fbed12a9f2e653c02",
          "Name": "",
          "Description": "Value of expression at line 4",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Util.BeamSection.CreateSectionString@string,string",
      "Id": "88bbc1cdf6d44111a6c9ad2febdb3879",
      "Inputs": [
        {
          "Id": "45502cbde7214832859c2b4ab3d643ef",
          "Name": "sectionType",
          "Description": "SectionType for a beam section\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "da8b27a13c344f799dfe74d9100b61c8",
          "Name": "sectionSize",
          "Description": "SectionSize for a beam section\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "333698140343433d9c68229da24e652c",
          "Name": "sectionName",
          "Description": "Beam section name",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns a concatenated string containing the SectionType, a fixed string separator \"#@ยง@#\" and the SectionSize.\n\nBeamSection.CreateSectionString (sectionType: string, sectionSize: string): string"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "\"AISC 14.1 Angle equal\";\n\"L4X4X7/16\";",
      "Id": "3d83663414d442ca85c16a22dfc73faf",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "df209df2f0934018b40cd7506be6d8cb",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b24ca18749d94452bb835ee2b5af27b3",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Beams.StraightBeam.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,string,string,int,bool",
      "Id": "1efbe65aaba54a7895e6925f8f53801d",
      "Inputs": [
        {
          "Id": "461d8ec02cd64475b5ff1fa45704f536",
          "Name": "start",
          "Description": "Input Start point of Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c80acbdbecbf47a4b0780c21c80f2ff1",
          "Name": "end",
          "Description": "Input End point of Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c2488f4f429d45fba4391a649db743ec",
          "Name": "orientation",
          "Description": "Section orientation\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "126e306edf3b444d842ca3e39f2babce",
          "Name": "modelRole",
          "Description": "Input Beam Model Role - Key Column of Model Table\n\nstring\nDefault value : Horizontal_Beam (disabled)",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e348644d73c8457686ca025f0ac91e73",
          "Name": "sectionName",
          "Description": "Input Beam Section size\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "622272b02c7646c3a2ea02a44dadae52",
          "Name": "refAxis",
          "Description": "Input Beam reference axis UpperLeft = 0, UpperSys = 1, UpperRight = 2, MidLeft = 3, SysSys = 4, MidRight = 5, LowerLeft = 6, LowerSys = 7, LowerRight = 8, ContourCenter = 9\n\nint\nDefault value : 5",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9c13d8e6c1cc463a9f4b13c1509853f7",
          "Name": "crossSectionMirror",
          "Description": "Input Beam Mirror Option\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "87d0887793ae418f9fc35bef78c1cf5f",
          "Name": "StraightBeam",
          "Description": "StraightBeam",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel straight beam between two points - inc ModelRole and Section Size\n\nStraightBeam.ByStartPointEndPoint (start: Point, end: Point, orientation: Vector, modelRole: string = Horizontal_Beam, sectionName: string, refAxis: int = 5, crossSectionMirror: bool = false): StraightBeam"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "Point.ByCoordinates(0,0,5000);\nPoint.ByCoordinates(2000,0,5000);\nVector.ZAxis();\n\"Bar\";\nVector.XAxis();",
      "Id": "873aa54c105f4c39a25c239f3e716d35",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7f8744d71f4e4266880289b166497eb2",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bee4bbc944114f7dbea03589fdaba86a",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "dd518b16cb2344f5bb53a2d1e6a7d512",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1d783736f39c4f5cac3ac48b97cea456",
          "Name": "",
          "Description": "Value of expression at line 4",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "97d91a224e314ce8a16cdedcaf81960e",
          "Name": "",
          "Description": "Value of expression at line 5",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "5000;",
      "Id": "c2a56e7d31994f749de14047978312bf",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "883998f3ee83483d8acfb1b8edb3e75c",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Beams.StraightBeam.ByStartPointDirectionLength@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,Autodesk.DesignScript.Geometry.Vector,double,string,string,int,bool",
      "Id": "ee2a01faca334163b5f26e4899e4560b",
      "Inputs": [
        {
          "Id": "7a011531b10145b4a35271be34cd4511",
          "Name": "start",
          "Description": "Input Start point of Beam\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e606a249db224895a5b595b7f63a94bb",
          "Name": "direction",
          "Description": "Input vector direction of beam\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d119c1883a49432eb183d2e5ff416fde",
          "Name": "orientation",
          "Description": "Section orientation\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "855f05334fa34668814258ca80ef0d43",
          "Name": "length",
          "Description": "Input Beam Length relative to Start Point\n\ndouble",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "86d6cf67fd504e17995f76f8d6b62973",
          "Name": "modelRole",
          "Description": "Input Beam Model Role - Key Column of Model Table\n\nstring\nDefault value : Horizontal_Beam",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f9199aa8043c4d4eae8739e087068db9",
          "Name": "sectionName",
          "Description": "Input Beam Section size\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a2cc019c8f444586a3c76e8c5130025e",
          "Name": "refAxis",
          "Description": "Input Beam reference axis UpperLeft = 0, UpperSys = 1, UpperRight = 2, MidLeft = 3, SysSys = 4, MidRight = 5, LowerLeft = 6, LowerSys = 7, LowerRight = 8, ContourCenter = 9\n\nint\nDefault value : 5",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fe4ed8a3bc3d478a93c2b9bc0cf28e8c",
          "Name": "crossSectionMirror",
          "Description": "Input Beam Mirror Option\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "fdc0655e50af4c0ea55c75204b5facdf",
          "Name": "StraightBeam",
          "Description": "StraightBeam",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel straight beam from a Point, direction and length - inc ModelRole and Section Size\n\nStraightBeam.ByStartPointDirectionLength (start: Point, direction: Vector, orientation: Vector, length: double, modelRole: string = Horizontal_Beam, sectionName: string, refAxis: int = 5, crossSectionMirror: bool = false): StraightBeam"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "\"AISC 14.1 Angle equal\";\n\"L4X4X7/16\";",
      "Id": "060ee43c97c444309dc43b0383942146",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "4479a39ff96f4330b53570f1215e2894",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2a09d8e8497e472cb9b29c3192468f2e",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Util.BeamSection.CreateSectionString@string,string",
      "Id": "10e32ee716744460853b6be376316fb9",
      "Inputs": [
        {
          "Id": "b7efe8083a514ddcb98677a8361eb2d9",
          "Name": "sectionType",
          "Description": "SectionType for a beam section\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "34176e19a7de45e3a3321182636f08e0",
          "Name": "sectionSize",
          "Description": "SectionSize for a beam section\n\nstring",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "98d1c76dbc6d408eb5fb2be4b040f256",
          "Name": "sectionName",
          "Description": "Beam section name",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns a concatenated string containing the SectionType, a fixed string separator \"#@ยง@#\" and the SectionSize.\n\nBeamSection.CreateSectionString (sectionType: string, sectionSize: string): string"
    },
    {
      "ConcreteType": "CoreNodeModels.CreateList, CoreNodeModels",
      "VariableInputPorts": true,
      "NodeType": "ExtensionNode",
      "Id": "f0c13fea5269443eab58d31aca5d9720",
      "Inputs": [
        {
          "Id": "0747bfabd28e4ae1a3df2a1ec2944d45",
          "Name": "item0",
          "Description": "Item Index #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bd2e87a660694d6996881af4603e5cad",
          "Name": "item1",
          "Description": "Item Index #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "37fcb27e2aca41c38fa44c938c19ecc5",
          "Name": "list",
          "Description": "A list",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Makes a new list out of the given inputs"
    },
    {
      "ConcreteType": "AdvanceSteel.Nodes.WeldConnectionType, AdvanceSteelNodesUI",
      "SelectedIndex": 2,
      "SelectedString": "InShop",
      "NodeType": "ExtensionNode",
      "Id": "68fbd608e1de412eb1dc3581f11f6799",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "d736b4f2c8e94d5b99b0429d1b303449",
          "Name": "Object Type",
          "Description": "string",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Set Weld Connection type - InShop or OnSite"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.ConnectionObjects.Welds.WeldPoint.ByPoint@Autodesk.DesignScript.Geometry.Point,AdvanceSteel.Nodes.SteelDbObject[],int",
      "Id": "e84b89cd8a6c437299b64301051897ff",
      "Inputs": [
        {
          "Id": "7c978f7f920e44e0bd984e09305b5b90",
          "Name": "point",
          "Description": "Input Weld Point Location\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f7e5d399ac774dabb234e7ee0bf54de5",
          "Name": "objectsToConnect",
          "Description": "Input Connected Objects\n\nSteelDbObject[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f3f805803f644b229ebe653a54f3fc4a",
          "Name": "connectionType",
          "Description": "Input Weld Type - 0-OnSite or 2-InShop\n\nint\nDefault value : 2",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "38f9830086b2403b904d2b519a921867",
          "Name": "WeldPoint",
          "Description": "WeldPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel Weld Pattern By Point\n\nWeldPoint.ByPoint (point: Point, objectsToConnect: SteelDbObject[], connectionType: int = 2): WeldPoint"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.ConnectionObjects.Welds.WeldLine.ByPolyCurve@Autodesk.DesignScript.Geometry.PolyCurve,AdvanceSteel.Nodes.SteelDbObject[],int",
      "Id": "37aeda71d4f44f369a69bc8a1ee3a39a",
      "Inputs": [
        {
          "Id": "a2e9a7072d56411d825980d35e04ad04",
          "Name": "polyCurve",
          "Description": "Input Weld PolyCurve\n\nPolyCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ad6857219ba944aca539a8168344acbf",
          "Name": "objectsToConnect",
          "Description": "Input Weld Connected Objects\n\nSteelDbObject[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "944d68c2010d4f55b20d58479e9ba203",
          "Name": "connectionType",
          "Description": "Input Weld Type - 0-OnSite or 2-InShop\n\nint\nDefault value : 2",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "14640463713543c485cc8eda2f3152bd",
          "Name": "WeldLine",
          "Description": "WeldLine",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an Advance Steel Weld Line By PolyCurve\n\nWeldLine.ByPolyCurve (polyCurve: PolyCurve, objectsToConnect: SteelDbObject[], connectionType: int = 2): WeldLine"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "AdvanceSteel.Nodes.Plates.Plate.ByLengthEdge@Autodesk.DesignScript.Geometry.Line,Autodesk.DesignScript.Geometry.Vector,double,double,double",
      "Id": "9115eadb1149429499c58ff544563520",
      "Inputs": [
        {
          "Id": "8a5b8836dcd645b88db047fdae4d1aaa",
          "Name": "line",
          "Description": "Input Dynamo Line\n\nLine",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "dab7aae799734674a894b13c875700f9",
          "Name": "normal",
          "Description": "Input Plate Normal\n\nVector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e70241c3d06043fb842fe82db6270b95",
          "Name": "width",
          "Description": "Input Plate Width\n\ndouble",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ec8e435151fe47a3bf70ad324777bb3a",
          "Name": "thickness",
          "Description": "Input Plate Thickness\n\ndouble",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "36072d6863d54f698cae4bc04d66fe71",
          "Name": "side",
          "Description": "Input Plate Side - 0, 0.5, 1\n\ndouble",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "581ed54dfa9e4aff812886bd5dd67ac2",
          "Name": "Plate",
          "Description": "Plate",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a rectangular Advance Steel Plate at the location of Dynamo Line with Width, including setting the side and thickness\n\nPlate.ByLengthEdge (line: Line, normal: Vector, width: double, thickness: double, side: double): Plate"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "2f5af2e55ce64b7291be32fe10ed102a",
      "Inputs": [
        {
          "Id": "0cb08bc4c4fc4b169beff685dea7c251",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "be90dc2cc330454695bb44395461983d",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "dda23a42cd8348099263f07ca34c7e0e",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "Point.ByCoordinates(0,-1200,0);\nPoint.ByCoordinates(1000,-1200,0);\n500;\n20;\n0;\nVector.ZAxis();",
      "Id": "599c7abc6ba24ee098af9a1373626fc5",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "a39b36f2c361425996c1816296d3f5c8",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a4fc40164e9c41b4b2f36943e4830188",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "191367d5b82449f7914fab85bdd2a81c",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "388be069e9da4084961ce5d28f1a9390",
          "Name": "",
          "Description": "Value of expression at line 4",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "bdabaa3525f24caf8e57ff795650bd1d",
          "Name": "",
          "Description": "Value of expression at line 5",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "377558d66c374eb5bfb79d5078b981bd",
          "Name": "",
          "Description": "Value of expression at line 6",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength@Autodesk.DesignScript.Geometry.CoordinateSystem,double,double",
      "Id": "bed1764830b34d328090b4f9ece45c1a",
      "Inputs": [
        {
          "Id": "dc66b07f8c804079941b162425ac9299",
          "Name": "cs",
          "Description": "CoordinateSystem\nDefault value : Autodesk.DesignScript.Geometry.CoordinateSystem.ByOrigin(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fc9d7354938346c096b8d317826cd727",
          "Name": "width",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0f75c06f27544a4da50481cdb7896543",
          "Name": "length",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "fab338273cf84029b92851879cfed227",
          "Name": "Rectangle",
          "Description": "Rectangle",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Rectangle centered at the input origin in the CoordinateSystem XY Plane, with specified width (X Axis length), and length (Y Axis length).\n\nRectangle.ByWidthLength (cs: CoordinateSystem = Autodesk.DesignScript.Geometry.CoordinateSystem.ByOrigin(0, 0, 0), width: double = 1, length: double = 1): Rectangle"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "400;\n900;",
      "Id": "edfd10bf82af47698d2ba311774dc7cc",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "ab3ba9d4f1f545f785dd7f0695d5a27f",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4ee136271b5446dd99764a32d8cf8e40",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.CoordinateSystem.ByOriginVectors@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Vector,Autodesk.DesignScript.Geometry.Vector,Autodesk.DesignScript.Geometry.Vector",
      "Id": "6b1ba2da61da457aaf423f55d286f446",
      "Inputs": [
        {
          "Id": "a531d8480a60411fb4c6ed086c3b2173",
          "Name": "origin",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "722b18e31518456a85e08f58d999c818",
          "Name": "xAxis",
          "Description": "Vector\nDefault value : Autodesk.DesignScript.Geometry.Vector.ByCoordinates(1, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "54eedba5993d40d08a750b3cb45aa703",
          "Name": "yAxis",
          "Description": "Vector\nDefault value : Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 1, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b908cbf462be4ab2971a187027b9a03c",
          "Name": "zAxis",
          "Description": "Vector\nDefault value : Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a04cc5070e2c41f7b1dfddf7167dfd08",
          "Name": "CoordinateSystem",
          "Description": "CoordinateSystem",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a CoordinateSystem at the origin with X and Y axis, with Z axis ignored completely. Input Vectors are normalized before creating the CoordinateSystem.\n\nCoordinateSystem.ByOriginVectors (origin: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), xAxis: Vector = Autodesk.DesignScript.Geometry.Vector.ByCoordinates(1, 0, 0), yAxis: Vector = Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 1, 0), zAxis: Vector = Autodesk.DesignScript.Geometry.Vector.ByCoordinates(0, 0, 1)): CoordinateSystem"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "Point.ByCoordinates(0,-950,0);\nVector.XAxis();\nVector.YAxis();\nVector.ZAxis();",
      "Id": "f98e5759b4bd403083514155d97bcc8b",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "b2bae2f4e31c4745bd765c28487e4cda",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a350426e5b974a7f91a35a5ef0eea2f6",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "26c1086e920e4e7d8597c501fa6fccf3",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "467d9823e7a441e4ae69e439af1eab9f",
          "Name": "",
          "Description": "Value of expression at line 4",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    }
  ],
  "Connectors": [
    {
      "Start": "1150e60fdb91433f94c7552ee6658d88",
      "End": "7a011531b10145b4a35271be34cd4511",
      "Id": "591c4369ddd943ff94d2a1ccaf51d561"
    },
    {
      "Start": "db0baf1428c6478b83518917ef36fba4",
      "End": "c2488f4f429d45fba4391a649db743ec",
      "Id": "2b2dd3f128ad4ace9750f72f32e901d6"
    },
    {
      "Start": "9991f2ec1b10434fbed12a9f2e653c02",
      "End": "126e306edf3b444d842ca3e39f2babce",
      "Id": "b5b1c077f3bc4de587ade6c42f2ac54b"
    },
    {
      "Start": "333698140343433d9c68229da24e652c",
      "End": "e348644d73c8457686ca025f0ac91e73",
      "Id": "b5707f3f84a5465eaf428ab9a7590e40"
    },
    {
      "Start": "df209df2f0934018b40cd7506be6d8cb",
      "End": "45502cbde7214832859c2b4ab3d643ef",
      "Id": "99a55491cfea4320bf5bf2b16c297b52"
    },
    {
      "Start": "b24ca18749d94452bb835ee2b5af27b3",
      "End": "da8b27a13c344f799dfe74d9100b61c8",
      "Id": "9779100ad646455f9d31c251a2fe5eba"
    },
    {
      "Start": "87d0887793ae418f9fc35bef78c1cf5f",
      "End": "0747bfabd28e4ae1a3df2a1ec2944d45",
      "Id": "15a26516c6574e08ae18d4d2762d9754"
    },
    {
      "Start": "7f8744d71f4e4266880289b166497eb2",
      "End": "461d8ec02cd64475b5ff1fa45704f536",
      "Id": "496c6963ced14130aa01ddf3bc80cf2a"
    },
    {
      "Start": "7f8744d71f4e4266880289b166497eb2",
      "End": "7c978f7f920e44e0bd984e09305b5b90",
      "Id": "6160cb0289d24dacae9218bb6bf7c90f"
    },
    {
      "Start": "bee4bbc944114f7dbea03589fdaba86a",
      "End": "c80acbdbecbf47a4b0780c21c80f2ff1",
      "Id": "98742c29c96a41acaae8a168bf1ba938"
    },
    {
      "Start": "dd518b16cb2344f5bb53a2d1e6a7d512",
      "End": "e606a249db224895a5b595b7f63a94bb",
      "Id": "5c7d8c0d04ee4d62a1451878534f159d"
    },
    {
      "Start": "1d783736f39c4f5cac3ac48b97cea456",
      "End": "86d6cf67fd504e17995f76f8d6b62973",
      "Id": "fad816ba8e5b4ea7acc96fcab6430256"
    },
    {
      "Start": "97d91a224e314ce8a16cdedcaf81960e",
      "End": "d119c1883a49432eb183d2e5ff416fde",
      "Id": "363f8ea44e18499592ae901366c20568"
    },
    {
      "Start": "883998f3ee83483d8acfb1b8edb3e75c",
      "End": "855f05334fa34668814258ca80ef0d43",
      "Id": "3afcc4010f544794a09ac293606c1ab2"
    },
    {
      "Start": "fdc0655e50af4c0ea55c75204b5facdf",
      "End": "bd2e87a660694d6996881af4603e5cad",
      "Id": "a6458fc06e8a4755b599e634ffe6320e"
    },
    {
      "Start": "4479a39ff96f4330b53570f1215e2894",
      "End": "b7efe8083a514ddcb98677a8361eb2d9",
      "Id": "3f70add8640b412382ea2e293ea3c973"
    },
    {
      "Start": "2a09d8e8497e472cb9b29c3192468f2e",
      "End": "34176e19a7de45e3a3321182636f08e0",
      "Id": "9639af4546fb4b62933a2a843e0c58c9"
    },
    {
      "Start": "98d1c76dbc6d408eb5fb2be4b040f256",
      "End": "f9199aa8043c4d4eae8739e087068db9",
      "Id": "add12c97a7c8479e8d7edfb215997770"
    },
    {
      "Start": "37fcb27e2aca41c38fa44c938c19ecc5",
      "End": "f7e5d399ac774dabb234e7ee0bf54de5",
      "Id": "e793f84f38f3476ab90a857bd4932758"
    },
    {
      "Start": "d736b4f2c8e94d5b99b0429d1b303449",
      "End": "f3f805803f644b229ebe653a54f3fc4a",
      "Id": "c2395ac9a2d6470ab0a24ddfef45f692"
    },
    {
      "Start": "d736b4f2c8e94d5b99b0429d1b303449",
      "End": "944d68c2010d4f55b20d58479e9ba203",
      "Id": "1a5247a3a4b042ff810b7d0773b33e41"
    },
    {
      "Start": "581ed54dfa9e4aff812886bd5dd67ac2",
      "End": "ad6857219ba944aca539a8168344acbf",
      "Id": "b3a8b8a847bf4924a4bdd365ce1b6e53"
    },
    {
      "Start": "dda23a42cd8348099263f07ca34c7e0e",
      "End": "8a5b8836dcd645b88db047fdae4d1aaa",
      "Id": "572e8f0883ce411889415e5c03329f5e"
    },
    {
      "Start": "a39b36f2c361425996c1816296d3f5c8",
      "End": "0cb08bc4c4fc4b169beff685dea7c251",
      "Id": "03a26a55fdc541df9ba591581677e07f"
    },
    {
      "Start": "a4fc40164e9c41b4b2f36943e4830188",
      "End": "be90dc2cc330454695bb44395461983d",
      "Id": "c2b35a124d314fba83bda95159de1d2c"
    },
    {
      "Start": "191367d5b82449f7914fab85bdd2a81c",
      "End": "e70241c3d06043fb842fe82db6270b95",
      "Id": "481f22bf905942e99c7b759530c78aed"
    },
    {
      "Start": "388be069e9da4084961ce5d28f1a9390",
      "End": "ec8e435151fe47a3bf70ad324777bb3a",
      "Id": "54b713d9553040bab2aa1186c9c6a81e"
    },
    {
      "Start": "bdabaa3525f24caf8e57ff795650bd1d",
      "End": "36072d6863d54f698cae4bc04d66fe71",
      "Id": "b4eddb0ab74444c19dadfdce509234f5"
    },
    {
      "Start": "377558d66c374eb5bfb79d5078b981bd",
      "End": "dab7aae799734674a894b13c875700f9",
      "Id": "ceacff0bfd8a40ffaa454e4cb3e5bdd6"
    },
    {
      "Start": "fab338273cf84029b92851879cfed227",
      "End": "a2e9a7072d56411d825980d35e04ad04",
      "Id": "7b5c80082d074f1299f25f275ccf4eb8"
    },
    {
      "Start": "ab3ba9d4f1f545f785dd7f0695d5a27f",
      "End": "fc9d7354938346c096b8d317826cd727",
      "Id": "39b46d162bd14489b63bbd9f23e615e4"
    },
    {
      "Start": "4ee136271b5446dd99764a32d8cf8e40",
      "End": "0f75c06f27544a4da50481cdb7896543",
      "Id": "96006a64988c4ad697159846e74b5805"
    },
    {
      "Start": "a04cc5070e2c41f7b1dfddf7167dfd08",
      "End": "dc66b07f8c804079941b162425ac9299",
      "Id": "44e5ce6b68d943ba8491af411e0227f5"
    },
    {
      "Start": "b2bae2f4e31c4745bd765c28487e4cda",
      "End": "a531d8480a60411fb4c6ed086c3b2173",
      "Id": "7c2a8d5947e943219611352f0cc81888"
    },
    {
      "Start": "a350426e5b974a7f91a35a5ef0eea2f6",
      "End": "722b18e31518456a85e08f58d999c818",
      "Id": "ce69cf7959144dd0a951484836e3cd9e"
    },
    {
      "Start": "26c1086e920e4e7d8597c501fa6fccf3",
      "End": "54eedba5993d40d08a750b3cb45aa703",
      "Id": "498ef1f56b2742778055d02cc6f72f74"
    },
    {
      "Start": "467d9823e7a441e4ae69e439af1eab9f",
      "End": "b908cbf462be4ab2971a187027b9a03c",
      "Id": "b63a8f914b4442d6a25c30c85c8b1d85"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.5.2.7915",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 11126.101471252978,
      "EyeY": 6436.3556487993474,
      "EyeZ": 14076.470737060758,
      "LookX": -14297.06892269562,
      "LookY": -6784.238468967862,
      "LookZ": -8999.6405440783819,
      "UpX": -0.13967847224954433,
      "UpY": 0.986285601537233,
      "UpZ": -0.08792403875149829
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "0d7d0194e1cb40818e02d464be6776dc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 201.10360485715489,
        "Y": 876.963022887656
      },
      {
        "ShowGeometry": true,
        "Name": "BeamSection.CreateSectionString",
        "Id": "88bbc1cdf6d44111a6c9ad2febdb3879",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 573.41960516046993,
        "Y": 692.2357092913
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "3d83663414d442ca85c16a22dfc73faf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 201.0,
        "Y": 704.23780009379993
      },
      {
        "ShowGeometry": true,
        "Name": "StraightBeam.ByStartPointEndPoint",
        "Id": "1efbe65aaba54a7895e6925f8f53801d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1148.8642996220522,
        "Y": 603.21392465663507
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "873aa54c105f4c39a25c239f3e716d35",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 177.72828228032608,
        "Y": 1075.8286890387662
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "c2a56e7d31994f749de14047978312bf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 564.68650047326173,
        "Y": 1242.78275197623
      },
      {
        "ShowGeometry": true,
        "Name": "StraightBeam.ByStartPointDirectionLength",
        "Id": "ee2a01faca334163b5f26e4899e4560b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1180.7434186943808,
        "Y": 1011.8714854350737
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "060ee43c97c444309dc43b0383942146",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 300.40418022529866,
        "Y": 1384.9365690094146
      },
      {
        "ShowGeometry": true,
        "Name": "BeamSection.CreateSectionString",
        "Id": "10e32ee716744460853b6be376316fb9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 648.45571393282489,
        "Y": 1384.1625428331515
      },
      {
        "ShowGeometry": true,
        "Name": "List Create",
        "Id": "f0c13fea5269443eab58d31aca5d9720",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1639.3405451718431,
        "Y": 717.4867548364191
      },
      {
        "ShowGeometry": true,
        "Name": "Weld Connection",
        "Id": "68fbd608e1de412eb1dc3581f11f6799",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1595.5544845845552,
        "Y": 847.74808002194186
      },
      {
        "ShowGeometry": true,
        "Name": "WeldPoint.ByPoint",
        "Id": "e84b89cd8a6c437299b64301051897ff",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1951.1679098655877,
        "Y": 911.37220722877169
      },
      {
        "ShowGeometry": true,
        "Name": "WeldLine.ByPolyCurve",
        "Id": "37aeda71d4f44f369a69bc8a1ee3a39a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1731.6766328829451,
        "Y": 2046.2104373630491
      },
      {
        "ShowGeometry": true,
        "Name": "Plate.ByLengthEdge",
        "Id": "9115eadb1149429499c58ff544563520",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1275.0577837781243,
        "Y": 2099.4584841465689
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "2f5af2e55ce64b7291be32fe10ed102a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 768.7899073734286,
        "Y": 2068.1059487579823
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "599c7abc6ba24ee098af9a1373626fc5",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 234.06533606698554,
        "Y": 2085.063504221087
      },
      {
        "ShowGeometry": true,
        "Name": "Rectangle.ByWidthLength",
        "Id": "bed1764830b34d328090b4f9ece45c1a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1372.3135595737926,
        "Y": 1932.7548083860111
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "edfd10bf82af47698d2ba311774dc7cc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1000.3564399841739,
        "Y": 2000.5343938293679
      },
      {
        "ShowGeometry": true,
        "Name": "CoordinateSystem.ByOriginVectors",
        "Id": "6b1ba2da61da457aaf423f55d286f446",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 749.75391253478278,
        "Y": 1767.7784739760043
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "f98e5759b4bd403083514155d97bcc8b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 309.11743445021693,
        "Y": 1740.1992029048131
      }
    ],
    "Annotations": [
      {
        "Id": "e855219557a24245b8c067bab7e75b79",
        "Title": "<Click here to edit the group title>",
        "Nodes": [
          "37aeda71d4f44f369a69bc8a1ee3a39a",
          "9115eadb1149429499c58ff544563520",
          "2f5af2e55ce64b7291be32fe10ed102a",
          "599c7abc6ba24ee098af9a1373626fc5",
          "bed1764830b34d328090b4f9ece45c1a",
          "edfd10bf82af47698d2ba311774dc7cc",
          "6b1ba2da61da457aaf423f55d286f446",
          "f98e5759b4bd403083514155d97bcc8b"
        ],
        "Left": 224.06533606698554,
        "Top": 1687.1992029048131,
        "Width": 1801.6112968159596,
        "Height": 609.25928124175584,
        "FontSize": 36.0,
        "InitialTop": 1740.1992029048131,
        "InitialHeight": 504.25928124175584,
        "TextblockHeight": 43.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "b6fffdffd807476d904dd00dbba7ea41",
        "Title": "<Click here to edit the group title>",
        "Nodes": [
          "0d7d0194e1cb40818e02d464be6776dc",
          "88bbc1cdf6d44111a6c9ad2febdb3879",
          "3d83663414d442ca85c16a22dfc73faf",
          "1efbe65aaba54a7895e6925f8f53801d",
          "873aa54c105f4c39a25c239f3e716d35",
          "c2a56e7d31994f749de14047978312bf",
          "ee2a01faca334163b5f26e4899e4560b",
          "060ee43c97c444309dc43b0383942146",
          "10e32ee716744460853b6be376316fb9",
          "f0c13fea5269443eab58d31aca5d9720",
          "68fbd608e1de412eb1dc3581f11f6799",
          "e84b89cd8a6c437299b64301051897ff"
        ],
        "Left": 167.72828228032608,
        "Top": 550.21392465663507,
        "Width": 2083.4396275852614,
        "Height": 952.94861817651645,
        "FontSize": 36.0,
        "InitialTop": 603.21392465663507,
        "InitialHeight": 926.72264435277953,
        "TextblockHeight": 43.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": -1122.3325832032938,
    "Y": -704.49961940157687,
    "Zoom": 1.0037008039354633
  }
}